// Examples, plain-language words and "how to undo" for the commands you're most likely to type (commands.js
// addInfo). Examples show in /help (▶ runs them) and as the hint while you type arguments; keywords and `args`
// (a word → the argument it means, e.g. vertical → 9:16) feed the plain-language search ("make it vertical",
// "dark theme", "turn off the click"). Nothing here reaches an agent: it's all local.
(() => {
  const VERT = { vertical: '9:16', portrait: '9:16', story: '9:16', stories: '9:16', reels: '9:16', reel: '9:16', shorts: '9:16', phone: '9:16', tall: '9:16',
    landscape: '16:9', horizontal: '16:9', widescreen: '16:9', wide: '16:9', youtube: '16:9', tv: '16:9', square: '1:1', insta: '4:5', instagram: '4:5', feed: '4:5', post: '4:5', fit: 'fit', cinema: '21:9', cinematic: '21:9' };
  const SL = '/undo-sliders (Ctrl+Z on the sliders)';
  Commands.addInfo({
    // ---------- Three.js Lab: your daily loop (Save, Shuffle, Tap, Freeze, frame sizes) ----------
    size: { boost: 1, examples: ['/size 9:16', '/size 16:9', '/size 4:5', '/size 1:1', '/size fit'], keywords: 'frame aspect ratio format resolution dimensions crop canvas preview vertical portrait landscape square widescreen', args: VERT, undo: '/size with the size before (or /size fit)' },
    freeze: { boost: 1, examples: ['/freeze', '/freeze off', '/freeze beat', '/freeze bar'], keywords: 'pause still hold stop picture frame image', undo: '/freeze again (or /freeze off)' },
    shuffle: { boost: 1, examples: ['/shuffle', '/shuffle colors', '/shuffle colors subtle', '/shuffle wild', '/shuffle favs bold seed 7'], keywords: 'random randomize variation dice mix sliders', args: { colours: 'colors', color: 'colors', gentle: 'subtle', little: 'subtle', crazy: 'wild', extreme: 'wild', big: 'bold' }, undo: '/unshuffle (Shift+R) or /undo-sliders' },
    reshuffle: { examples: ['/reshuffle'], keywords: 'forward next shuffle redo', undo: '/unshuffle' },
    unshuffle: { examples: ['/unshuffle'], keywords: 'previous shuffle back undo shuffle' },
    'save-sliders': { examples: ['/save-sliders'], keywords: 'save keep store write commit sliders code', undo: 'Ctrl+Z in the code view' },
    'save-look': { examples: ['/save-look', '/save-look Drop neon'], keywords: 'save keep store preset look snapshot', undo: '/look delete <name>' },
    look: { examples: ['/look', '/look next', '/look random', '/look save Drop'], undo: SL },
    tap: { boost: 1, examples: ['/tap', '/tap 128', '/tap one'], keywords: 'tempo bpm beat tap downbeat' },
    bpm: { examples: ['/bpm 128', '/bpm x2', '/bpm half', '/bpm auto'], keywords: 'tempo speed beats per minute grid', args: { double: 'x2', twice: 'x2', halve: 'half', detect: 'auto', automatic: 'auto' }, undo: 'Ctrl+Z in the Lab timeline' },
    live: { examples: ['/live system', '/live mic', '/live off', '/live gain 2'], keywords: 'sound audio listen spotify youtube microphone input music react', args: { spotify: 'system', computer: 'system', desktop: 'system', microphone: 'mic', stop: 'off' } },
    kick: { examples: ['/kick'], keywords: 'marker drum beat hit timeline', undo: 'Ctrl+Z in the Lab timeline' },
    snare: { examples: ['/snare'], keywords: 'marker drum clap timeline', undo: 'Ctrl+Z in the Lab timeline' },
    hit: { examples: ['/hit'], keywords: 'marker accent timeline', undo: 'Ctrl+Z in the Lab timeline' },
    autobars: { examples: ['/autobars'], keywords: 'auto bars fit triggers sound analyze', undo: 'Ctrl+Z in the Lab timeline' },
    preset: { examples: ['/preset techno / house', '/preset hip-hop / trap'], keywords: 'triggers genre style music' },
    'trigger-preset': { examples: ['/trigger-preset busy', '/trigger-preset calm', '/trigger-preset techno'], keywords: 'triggers genre behavior reactive' },
    triggers: { examples: ['/triggers', '/triggers off'], keywords: 'panel lightning reactive' },
    loop: { examples: ['/loop 4 bars', '/loop 0:32 0:48', '/loop bar', '/loop off'], keywords: 'repeat section cycle region', undo: '/loop off' },
    cue: { examples: ['/cue Drop', '/cue next', '/cue prev'], keywords: 'section marker spot jump hot cue', undo: 'Ctrl+Z in the Lab timeline' },
    cues: { examples: ['/cues'], keywords: 'sections list markers' },
    sections: { examples: ['/sections', '/sections looks'], keywords: 'intro build drop break outro song parts structure' },
    song: { examples: ['/song play', '/song pause', '/song seek 1:20', '/song speed 0.5', '/song mute'], keywords: 'music track audio playback play pause seek' },
    slider: { examples: ['/slider glow 2.5', '/slider tint #ff3cac', '/slider speed 0.5'], keywords: 'set value control parameter knob tweak', undo: SL },
    'find-slider': { examples: ['/find-slider glow'], keywords: 'search slider control parameter' },
    'fav-slider': { examples: ['/fav-slider glow'], keywords: 'favorite star slider top' },
    'lock-slider': { examples: ['/lock-slider tint'], keywords: 'lock keep protect freeze slider', undo: '/unlock-slider' },
    slot: { examples: ['/slot A', '/slot B save', '/slot C clear'], keywords: 'memory recall save slot preset ab' },
    morph: { examples: ['/morph 50%', '/morph auto 8', '/morph swap'], keywords: 'blend crossfade interpolate between slots', undo: SL },
    tame: { examples: ['/tame', '/tame 0.25'], keywords: 'calm back reduce halfway soften', undo: SL },
    exaggerate: { examples: ['/exaggerate', '/exaggerate 2'], keywords: 'more push stronger amplify extreme', undo: SL },
    'reset-sliders': { examples: ['/reset-sliders'], keywords: 'reset default original code values', undo: SL },
    'undo-sliders': { examples: ['/undo-sliders'], keywords: 'undo slider back revert' },
    'paste-sliders': { examples: ['/paste-sliders'], undo: SL },
    knob: { examples: ['/knob glow 0.8'], undo: SL },
    'move-slider': { examples: ['/move-slider glow lfo 4', '/move-slider hue walk', '/move-slider size beat 1 50%'], keywords: 'animate automate lfo wave modulate oscillate', undo: '/move-slider <slider> off' },
    'follow-music': { examples: ['/follow-music glow kick', '/follow-music size bass 0.6'], keywords: 'react audio reactive sound band kick bass', undo: '/follow-music <slider> off' },
    fx: { examples: ['/fx', '/fx bloom', '/fx glitch --top'], keywords: 'effect filter postprocess post layer', undo: 'Delete the layer (Layers panel) or Ctrl+Z' },
    'fx-picker': { examples: ['/fx-picker', '/fx-picker looks'], keywords: 'effects picker browse library' },
    surprise: { examples: ['/surprise', '/surprise look', '/surprise palette'], keywords: 'random effect lucky inspire', undo: 'Ctrl+Z in the Lab' },
    'look-apply': { examples: ['/look-apply', '/look-apply --colors'], keywords: 'look style grade color preset' },
    'fx-palette': { examples: ['/fx-palette', '/fx-palette --only'], keywords: 'palette colors scheme' },
    'lab-palette': { examples: ['/lab-palette #ff3cac #2b86c5 #784ba0', '/lab-palette https://coolors.co/…'], keywords: 'palette colors coolors hex' },
    layer: { examples: ['/layer top', '/layer hide 2', '/layer solo', '/layer show all'], keywords: 'layers select hide show solo visibility' },
    'layer-add': { examples: ['/layer-add', '/layer-add visualizer', '/layer-add text --above'], keywords: 'add new layer template', undo: 'Delete the layer (Layers panel)' },
    blend: { examples: ['/blend glow', '/blend screen', '/blend multiply'], keywords: 'blend mode composite mix' },
    still: { examples: ['/still', '/still 9:16', '/still 1:1 copy'], keywords: 'png picture screenshot export image capture frame save' },
    stills: { examples: ['/stills cues', '/stills sizes'], keywords: 'pngs pictures export batch' },
    record: { examples: ['/record loop', '/record 8 bars', '/record 15s 60 hq', '/record stop'], keywords: 'video capture export render mp4 webm' },
    present: { examples: ['/present'], keywords: 'fullscreen show perform projector' },
    console: { examples: ['/console', '/console clear', '/console copy'], keywords: 'log errors output debug' },
    'fix-errors': { examples: ['/fix-errors'], keywords: 'errors bug broken fix director console' },
    'frame-to-director': { examples: ['/frame-to-director', '/frame-to-director compare'], keywords: 'screenshot attach director picture send' },
    onion: { examples: ['/onion pin', '/onion wipe', '/onion off'], keywords: 'compare before after frame pin overlay' },
    guides: { examples: ['/guides'], keywords: 'composition thirds golden ratio grid overlay' },
    fps: { examples: ['/fps 30', '/fps 60', '/fps max'], keywords: 'framerate frame rate performance speed' },
    fit: { examples: ['/fit'], keywords: 'fit preview window', undo: '/size with the size before' },
    snap: { examples: ['/snap 1/8', '/snap bar', '/snap off'], keywords: 'grid quantize snapping' },
    quantize: { examples: ['/quantize on', '/quantize off'], keywords: 'grid snap taps exact' },
    'click-track': { examples: ['/click-track on', '/click-track off'], keywords: 'metronome click beep beat check' },
    sketch: { examples: ['/sketch new', '/sketch duplicate', '/sketch rename Neon tunnel'], keywords: 'project file open new scene' },
    sketches: { examples: ['/sketches', '/sketches browse'], keywords: 'projects list open files' },
    lab: { examples: ['/lab', '/lab shader', '/lab model'], keywords: 'three threejs open lab tool' },
    'lab-state': { examples: ['/lab-state'], keywords: 'status info what current lab' },
    animate: { examples: ['/animate bounce in', '/animate heartbeat'], keywords: 'keyframes animation motion' },
    ease: { examples: ['/ease elastic', '/ease bounce'], keywords: 'easing curve keyframes' },
    'contact-sheet': { examples: ['/contact-sheet'], keywords: 'overview grid thumbnails frames' },
    'restart-sketch': { examples: ['/restart-sketch'], keywords: 'restart reload rerun reset simulation' },
    'edit-scene': { examples: ['/edit-scene', '/edit-scene off'], keywords: 'move objects gizmo 3d transform' },
    'show-code': { examples: ['/show-code', '/show-code off'], keywords: 'code editor view hide' },
    nodes: { examples: ['/nodes', '/nodes code'], keywords: 'node graph visual programming' },
    'beat-grid': { examples: ['/beat-grid numbers', '/beat-grid sections'], keywords: 'timeline grid look lines' },
    blackout: { examples: ['/blackout', '/blackout off'], keywords: 'black fade dark screen' },
    'next-frame': { examples: ['/next-frame'], keywords: 'step frame forward advance' },
    safe: { examples: ['/safe tiktok', '/safe reels', '/safe off'], keywords: 'safe zone ui overlay margins captions', args: { instagram: 'reels', youtube: 'shorts' } },
    // ---------- Video Review ----------
    video: { examples: ['/video', '/video final'], keywords: 'review player renders open' },
    videos: { examples: ['/videos', '/videos 9:16', '/videos fav', '/videos #client'], keywords: 'renders list library files' },
    play: { examples: ['/play'], keywords: 'start video playback' },
    pause: { examples: ['/pause'], keywords: 'stop video playback' },
    step: { examples: ['/step 1', '/step -5'], keywords: 'frame next previous advance' },
    grab: { examples: ['/grab', '/grab save', '/grab chat'], keywords: 'frame screenshot capture still' },
    crop: { examples: ['/crop 9:16', '/crop 4:5'], keywords: 'reframe crop social format', args: VERT },
    'export-all': { examples: ['/export-all', '/export-all blur'], keywords: 'export socials formats batch render' },
    formats: { examples: ['/formats'], keywords: 'social sizes formats aspect' },
    scopes: { examples: ['/scopes'], keywords: 'histogram waveform luma color' },
    draw: { examples: ['/draw arrow', '/draw circle'], keywords: 'annotate markup sketch arrow note' },
    resolve: { examples: ['/resolve 2', '/resolve 1 3 4', '/resolve all'], keywords: 'done finished note check', undo: '/reopen <n>' },
    'send-feedback': { examples: ['/send-feedback', '/send-feedback claude sheet'], keywords: 'feedback notes director send' },
    sheet: { examples: ['/sheet', '/sheet 12'], keywords: 'contact sheet thumbnails' },
    mirror: { examples: ['/mirror'], keywords: 'flip horizontal mirror' },
    view: { examples: ['/view luma', '/view r', '/view normal'], keywords: 'channel luma invert contrast' },
    volume: { examples: ['/volume 50', '/volume 0'], keywords: 'loud sound audio level mute' },
    // ---------- chats ----------
    new: { examples: ['/new', '/new Draft a shader for the drop'], keywords: 'chat fresh start conversation' },
    open: { examples: ['/open shader', '/open drop visuals'], keywords: 'chat go find conversation' },
    recent: { examples: ['/recent', '/recent 20', '/recent claude'], keywords: 'chats latest list conversations' },
    rename: { examples: ['/rename Drop visuals v2'], keywords: 'title name chat', undo: '/undo' },
    pin: { examples: ['/pin'], keywords: 'chat top favorite', undo: '/unpin' },
    tag: { examples: ['/tag music, lab'], keywords: 'label chat', undo: '/untag <tag> or /undo' },
    delete: { examples: ['/delete'], keywords: 'remove chat trash', undo: '/undo or /restore' },
    archive: { examples: ['/archive'], keywords: 'hide chat', undo: '/unarchive or /undo' },
    forget: { examples: ['/forget last', '/forget coffee'], undo: '/undo' },
    'clear-draft': { examples: ['/clear-draft'], undo: '/undo' },
    search: { examples: ['/search bloom', '/search "frame size"'], keywords: 'find grep every chat messages' },
    find: { examples: ['/find shader'], keywords: 'search this chat highlight' },
    copy: { examples: ['/copy', '/copy code', '/copy all'], keywords: 'clipboard reply' },
    compact: { examples: ['/compact'], keywords: 'context summary tokens shrink' },
    retry: { examples: ['/retry', '/retry opus'], keywords: 'regenerate again redo reply' },
    continue: { examples: ['/continue'], keywords: 'more go on keep going' },
    summarize: { examples: ['/summarize', '/summarize 5 bullets'], keywords: 'summary recap overview' },
    tldr: { examples: ['/tldr'], keywords: 'short summary one sentence' },
    export: { examples: ['/export', '/export html', '/export md clipboard'], keywords: 'save chat file markdown' },
    note: { examples: ['/note', '/note last', '/note an idea for the drop'], keywords: 'notes save keep' },
    model: { examples: ['/model', '/model opus', '/model default'], keywords: 'model llm switch engine' },
    effort: { examples: ['/effort low', '/effort high'], keywords: 'think reasoning harder' , args: { harder: 'high', more: 'high', less: 'low', quick: 'low', fast: 'low', max: 'xhigh' } },
    stop: { examples: ['/stop'], keywords: 'cancel halt abort reply' },
    'stop-all': { examples: ['/stop-all'], keywords: 'cancel halt every reply' },
    astra: { examples: ['/astra what do you think of this shader?'], keywords: 'chatgpt gpt codex openai ask' },
    duo: { examples: ['/duo name three looks for a techno drop'], keywords: 'both side by side compare claude astra' },
    opinion: { examples: ['/opinion', '/opinion astra'], keywords: 'second opinion review check other' },
    handoff: { examples: ['/handoff', '/handoff astra'], keywords: 'continue other agent switch' },
    remember: { examples: ['/remember I work at 128 BPM by default'], keywords: 'memory fact keep', undo: '/forget <words>' },
    memory: { examples: ['/memory', '/memory edit'], keywords: 'remembered facts' },
    draft: { examples: ['/draft Make the bloom pulse on the kick'], keywords: 'compose write message box' },
    template: { examples: ['/template', '/template bug report'], keywords: 'starter brief prompt fill' },
    queue: { examples: ['/queue then make it faster', '/queue list'], keywords: 'later wait next message' },
    screenshot: { examples: ['/screenshot', '/screenshot lab'], keywords: 'picture capture attach window' },
    attach: { examples: ['/attach'], keywords: 'file upload add picture' },
    zoom: { examples: ['/zoom +', '/zoom 120%', '/zoom 0'], keywords: 'text size bigger smaller font scale', args: { bigger: '+', larger: '+', smaller: '-', reset: '0', normal: '0' } },
    width: { examples: ['/width wide', '/width narrow', '/width full'], keywords: 'messages column wide narrow' },
    focus: { examples: ['/focus'], keywords: 'distraction free only chat hide panels' },
    // ---------- look, meter, app ----------
    theme: { examples: ['/theme molten', '/theme next', '/theme random', '/theme midnight'], keywords: 'look skin appearance colors style dark light mode', args: { dark: 'midnight', night: 'midnight', black: 'obsidian', bright: 'light', white: 'light', day: 'light', default: 'forgeheart', original: 'classic', old: 'classic', chrome: 'chrome-forge', glass: 'glass-ember', neon: 'neon-anvil', gold: 'gold-leaf', purple: 'midnight-violet', violet: 'midnight-violet', green: 'jade-furnace', red: 'bloodmoon', pink: 'rose-gold' }, undo: '/theme prev' },
    appearance: { examples: ['/appearance', '/appearance save mine'], keywords: 'look theme textures glow motion settings', undo: '/appearance reset' },
    accent: { examples: ['/accent violet', '/accent #ff3cac', '/accent reset'], keywords: 'color highlight gold', undo: '/accent reset' },
    glow: { examples: ['/glow 30', '/glow +', '/glow 0'], keywords: 'bloom shine brightness', undo: '/glow 50' },
    density: { examples: ['/density compact', '/density comfortable'], keywords: 'spacing tight roomy compact', args: { tight: 'compact', small: 'compact', roomy: 'comfortable', big: 'comfortable' }, undo: '/density normal' },
    motion: { examples: ['/motion calm', '/motion off'], keywords: 'animation reduce calm', args: { less: 'calm', none: 'off', stop: 'off' } },
    usage: { examples: ['/usage', '/usage models'], keywords: 'tokens dashboard stats cost' },
    tokens: { examples: ['/tokens', '/tokens today'], keywords: 'usage count cost' },
    budget: { examples: ['/budget Claude 300k', '/budget off'], keywords: 'limit daily tokens cap', undo: '/budget <agent> off' },
    meter: { examples: ['/meter pill', '/meter strip', '/meter off'], keywords: 'token meter strip bar', undo: '/meter strip' },
    calc: { examples: ['/calc 1080*16/9', '/calc 60/128*4'], keywords: 'math calculate compute sum' },
    time: { examples: ['/time'], keywords: 'date clock now' },
    alias: { examples: ['/alias vert /run /size 9:16 ; /freeze', '/alias'], keywords: 'shortcut custom own command macro', undo: '/unalias <name>' },
    run: { examples: ['/run /size 9:16 ; /freeze', '/run /shuffle ; /wait 2s ; /unshuffle'], keywords: 'chain sequence several multiple' },
    do: { examples: ['/do settings', '/do restart'], keywords: 'action palette anything' },
    'director-ask': { examples: ['/director-ask make the bloom pulse on every kick'], keywords: 'three director agent ask' },
    'director-cost': { examples: ['/director-cost'], keywords: 'tokens price director' },
    dock: { examples: ['/dock hide', '/dock show', '/dock width 420'], keywords: 'director chat panel side' },
    undo: { examples: ['/undo'], keywords: 'revert back take back' },
    notes: { examples: ['/notes'], keywords: 'notebook open' },
    todo: { examples: ['/todo export the 9:16 version'], keywords: 'task checklist remind' },
    inbox: { examples: ['/inbox idea: strobe on the snare'], keywords: 'capture quick note' },
    library: { examples: ['/library', '/library music'], keywords: 'prompts presets' },
    kit: { examples: ['/kit', '/kit bpm'], keywords: 'tools color easing bpm' },
    color: { examples: ['/color #ff3cac', '/color hotpink'], keywords: 'colour hex rgb convert' },
    'kit-bpm': { examples: ['/kit-bpm 128', '/kit-bpm 470ms'], keywords: 'note lengths tempo ms' },
    tc: { examples: ['/tc 00:01:00:00 + 12f', '/tc 8 bars @128bpm'], keywords: 'timecode frames duration' },
    forge: { examples: ['/forge', '/forge tasks'], keywords: 'forgeheart game project' },
    'forge-status': { examples: ['/forge-status'], keywords: 'game debug status' },
    backup: { examples: ['/backup now', '/backup list'], keywords: 'save copy safety' },
    echo: { examples: ['/echo hello'], keywords: 'print say show' },
    // ---------- the command bar's own ----------
    'hide-feature': { undo: '/show-feature <name>' },
    'remember-all': { undo: '/forget <words>' },
    'pin-msg': { undo: '/unmark <#>' },
    bookmark: { undo: '/unmark <#>' },
    react: { undo: '/unmark <#>' },
    folder: { undo: '/folder none' },
    'undo-edit': { examples: ['/undo-edit'], keywords: 'director revert code edit' },
    'nodes-undo': { examples: ['/nodes-undo'] },
  });
})();
