// Commands page data (round 11): what the page says about the commands, kept apart from the ≈ 930 call sites.
// - DESC: one clear sentence for the ≈ 150 commands used most (the registry's own `desc` stays for /help and chats).
// - ABOUT: "what it does / when to use it" for the principal commands.
// - Q: explicit questions for the ≈ 60 commands whose args string says too little ("<9:16|…>" → "Which frame size?").
//   Each: { q: [{ title, kind: choice|yesno|count|text|command, required, options: [label | [label, value, hint]],
//   free (a box to type too), placeholder, prefix }], repeat: false | true | 'every' }. Plain data (Node-testable).
// - SCENES / sceneFor(def): which little preview animation a command gets (cmdpage-previews.js draws it).
const CmdPageData = (() => {
  const o = (label, value = label, hint) => (hint ? { label, value, hint } : { label, value });
  const SIZES = [o('9:16 vertical (Reels, TikTok)', '9:16'), o('16:9 wide (YouTube)', '16:9'), o('4:5 feed', '4:5'), o('1:1 square', '1:1'), o('Fit the preview', 'fit')];

  const DESC = {
    // chats
    help: 'Shows every command, searchable, with examples and keys.',
    new: 'Starts a fresh chat with this agent, and sends your first message if you give one.',
    compact: 'Folds the chat so far into a short summary so later messages cost fewer tokens; every message stays readable.',
    stop: 'Stops the reply that is being written right now.',
    retry: 'Writes the last reply again, optionally with another model.',
    copy: 'Copies the last reply (or its code, a message, your messages or the whole chat) to the clipboard.',
    read: 'Reads a reply aloud with the computer\'s voice.',
    undo: 'Takes back the last thing you did here: a chat action, an edit in the video editor, a move on the board.',
    screenshot: 'Puts a picture of the window (or the Lab) into your message.',
    do: 'Runs any action from the Ctrl/⌘+K palette by its name.',
    astra: 'Sends a message to Astra (ChatGPT) without leaving where you are.',
    claude: 'Sends a message to Claude without leaving where you are.',
    handoff: 'Hands this chat to the other agent with a short summary so it carries on.',
    jam: 'Claude and Astra take turns building a music visual in the Lab; you keep the best round.',
    opinion: 'Asks the other agent for a second opinion on the last reply.',
    decide: 'Lets Astra pick for you (a look, an effect, a palette, the frame size, the app look), with Undo.',
    doctor: 'Checks Claude Code and Codex in one card and offers one-click fixes.',
    summarize: 'Asks for a compact summary of this chat so far.',
    tldr: 'Turns the last reply into one sentence.',
    shorter: 'Asks for a shorter version of the last reply.',
    simpler: 'Asks for a simpler explanation of the last reply.',
    continue: 'Asks the agent to carry on where its reply stopped.',
    find: 'Highlights every match in this chat; Enter jumps to the next.',
    search: 'Searches the messages of every chat.',
    bookmark: 'Bookmarks a message (the last reply by default) so you can find it again.',
    pin: 'Pins this chat to the top of the list (again to unpin).',
    rename: 'Renames this chat.',
    branch: 'Starts a new chat from a message to try another direction; this one stays as it is.',
    delete: 'Moves this chat to Recently deleted for 30 days (Undo brings it back).',
    export: 'Saves this chat as Markdown, HTML, JSON or text (or copies it).',
    thinking: 'Opens or closes every "Thought process" block in the chat.',
    things: 'Lists what this chat made: captures, frames, renders, board items, scenes.',
    'chat-context': 'Shows what this chat works with (board, scene, sequence, project) and how it uses it.',
    attach: 'Attaches files to your next message.',
    'attach-frame': 'Attaches the Lab picture on screen to your next message.',
    'attach-board': 'Attaches the board\'s vibe (never its media) to your next message.',
    draft: 'Puts text in the message box without sending it.',
    queue: 'Queues a message that sends itself when the current reply ends.',
    persona: 'Makes the agent answer as a role for your next message.',
    tone: 'Sets the tone of the answers (sent once with your next message).',
    remember: 'Saves a fact this agent keeps in mind in every chat.',
    forget: 'Removes remembered facts that contain your words.',
    memory: 'Shows what this agent remembers about you.',
    // agents and the two AIs together
    duo: 'Claude and Astra answer side by side; you pick one or merge them.',
    relay: 'One agent drafts, the other improves it, in turns.',
    debate: 'Both agents answer, read each other and reply for a few rounds, then one merged answer.',
    council: 'Several seats answer the same question and a chair writes the final answer.',
    'compare-agents': 'Sends the same task to different models or agents and shows them side by side.',
    'ask-astra': 'Gets a quick answer from Astra right inside this chat.',
    'director-engine': 'Switches a docked director (Three or Video) between Claude and Astra, same chat and scene.',
    model: 'Shows or changes the model this chat uses.',
    effort: 'Sets how hard this agent thinks (higher is slower and costs more tokens).',
    engines: 'Lists every Claude Code / Codex copy on this computer and which one is used.',
    login: 'Signs this agent\'s engine in, in its own window.',
    'stop-all': 'Stops every reply in progress, in every chat.',
    task: 'Shows what this director chat is making and how far it got.',
    'undo-edit': 'Takes back the director\'s last code edit in the Lab.',
    // the Lab
    'save-sliders': 'Writes the selected layer\'s slider values into its code (Ctrl/⌘+S).',
    shuffle: 'Gives the sliders new random values: all of them or a group, gently or wildly.',
    tap: 'Taps the tempo; with a number it sets the BPM, "one" puts the downbeat at the playhead.',
    freeze: 'Freezes the picture while the music plays on; again to unfreeze.',
    size: 'Sets the Lab picture to an exact social frame size (9:16, 16:9, 4:5, 1:1) or fits it.',
    live: 'Makes the Lab react to live sound: the computer\'s sound, the microphone, or off.',
    present: 'Shows the preview alone, fullscreen (Esc leaves).',
    sketches: 'Lists your sketches, newest first (or browses them as pictures).',
    scene: 'Shows, links or replaces the Lab scene this director chat owns.',
    look: 'Opens the Appearance picker; in the Lab it switches between your saved looks.',
    still: 'Saves a still picture at the exact frame size.',
    sequence: 'Shows the Lab sequence: a video timeline of your scenes, footage, titles and the song.',
    'save-look': 'Saves the current slider values as a look you can come back to.',
    'save-one': 'Writes just one slider into the code; your other changes stay live.',
    reshuffle: 'Goes forward to the next shuffle (or makes a new one).',
    unshuffle: 'Goes back to the shuffle before (Shift+R).',
    'undo-sliders': 'Undoes the last slider change.',
    'reset-sliders': 'Puts the selected layer\'s sliders back to the values in the code.',
    surprise: 'Applies a random filter, layer, look or palette.',
    tame: 'Moves every changed slider halfway back toward the code (after a wild shuffle).',
    exaggerate: 'Pushes every slider change further away from the code.',
    sliders: 'Shows or hides the layers & sliders panel.',
    slider: 'Sets one slider by its name to a value.',
    lab: 'Opens the Three.js Lab (or one of its tools).',
    'lab-state': 'Tells what the Lab shows now: sketch, layer, frame size, song, BPM, live sound.',
    console: 'Shows, hides, clears or copies the Lab console.',
    'edit-scene': 'Lets you move the scene\'s objects around in 3D.',
    fit: 'Fits the picture to the preview instead of an exact size.',
    fps: 'Sets the preview frame rate (max, 60 or 30).',
    record: 'Records the Lab picture as a video (the loop, the song, N bars or seconds); outside the Lab it records Hearth itself.',
    stills: 'Saves a folder of stills: one at every cue, or this frame in all four sizes.',
    'contact-sheet': 'Makes one picture with frames of the whole piece.',
    layer: 'Selects a layer, or hides, shows or solos one.',
    'layer-add': 'Adds a ready-made layer (visualizer, background, text, 3D…).',
    fx: 'Adds a filter layer above the selected layer.',
    'fx-picker': 'Opens the searchable effects picker (X in the Lab).',
    blend: 'Sets how the selected layer blends (glow, screen, multiply…).',
    bpm: 'Sets the tempo of the beat grid.',
    downbeat: 'Sets bar 1: as detected, at the playhead, or at a time.',
    kick: 'Drops a kick marker at the playhead (K).',
    snare: 'Drops a snare marker at the playhead (S).',
    hit: 'Drops a hit marker at the playhead (H).',
    marker: 'Drops a kick, snare or hit marker at the playhead.',
    cues: 'Lists the song\'s cues.',
    sections: 'Marks the song\'s parts (intro, build, drop…) as cues looks can follow.',
    drops: 'Lists the drops found in the song and jumps to one.',
    'make-it-react': 'Makes sensible sliders follow the kick, bass and loudness in one click.',
    'mark-kicks': 'Turns the hits found in the audio into markers you can edit.',
    'follow-music': 'Makes one slider follow a part of the music (kick, bass, highs, loudness…).',
    'beat-grid': 'Changes how the timeline shows the beat grid.',
    analyze: 'Shows what Hearth found in the song: tempo, bar 1, sections, drops, hits.',
    song: 'Plays, pauses, seeks, slows or loads the song.',
    loop: 'Loops a part of the song: two times, N bars from the playhead, or off.',
    snap: 'Sets what markers and loops snap to (bars, beats, hits or off).',
    'auto-preset': 'Picks the trigger preset from the song\'s style and tempo.',
    autobars: 'Fits the trigger bars to the sound playing now.',
    triggers: 'Opens or closes the ⚡ Triggers panel.',
    'trigger-preset': 'Sets the ⚡ triggers for a style of music or a behaviour.',
    'look-apply': 'Applies a saved look: its palette, recolored layer and filters.',
    morph: 'Morphs the sliders between two save slots.',
    recolor: 'Puts the palette into the selected layer\'s color sliders.',
    'lab-palette': 'Sets the sketch palette from hex codes or a coolors link.',
    'stage-window': 'Runs the sketch in its own Stage window.',
    'lab-focus': 'Makes the Lab almost fullscreen (Esc leaves).',
    'show-code': 'Shows or hides the code.',
    sketch: 'Opens, creates, renames or duplicates a sketch.',
    'restart-sketch': 'Restarts the sketch from scratch (fresh page, GPU and sound).',
    'fix-errors': 'Sends the console\'s errors to the Three Director to fix.',
    arrange: 'Builds a Lab sequence from your scenes on the song: cuts on bars, transitions chosen for you.',
    'add-scene': 'Puts a scene on the Lab sequence.',
    'sequence-render': 'Renders the Lab sequence frame by frame into a video.',
    'scene-timeline': 'Shows and drives the scene\'s own timeline (no song needed).',
    footage: 'Works with the Lab\'s video footage frame by frame.',
    'frame-step': 'Steps the footage forward or back by N frames.',
    'next-frame': 'Steps one frame forward (freezes first).',
    'goto-frame': 'Jumps to an exact frame or timecode.',
    'motion-kit': 'Opens the motion-design kit: Hearth on screen, kinetic type, camera moves, logo reveals.',
    kinetic: 'Adds animated words that fit the frame (type-on, slam, wave…).',
    'camera-move': 'Adds a camera move as a layer (dolly, orbit, whip pan…).',
    'logo-reveal': 'Adds a logo reveal of the Hearth flame or the Forgeheart anvil.',
    // board, capture, video
    board: 'Opens the mood board (or switches to a board by name).',
    'board-use': 'Attaches the board\'s vibe to your next message so the chat uses it as a mood, never as footage.',
    'board-add': 'Adds a website, a picture, a clip, colors or a note to the board.',
    'board-new': 'Makes a new board, optionally from a template.',
    vibe: 'Shows the vibe of the board (or a selection) here, without sending anything.',
    ref: 'Attaches the vibe of the references matching your words to your next message.',
    'board-layout': 'Arranges the board in a grid, masonry, timeline, collage or rainbow.',
    'board-grid': 'Turns snapping to a grid on or off.',
    'board-present': 'Presents the board by flying between its frames.',
    capture: 'Opens the capture menu: screenshots, recordings, tours and the frame reader.',
    rec: 'Records Hearth itself (the window, a tool, a region), with or without sound.',
    'record-presets': 'Picks a recording preset (Promo, Reel 9:16, Tutorial, YouTube…).',
    tour: 'Plays a hands-free scripted tour of Hearth, ready to record.',
    frames: 'Reads frames of any video exactly: at a time, every N, scene changes, a contact sheet.',
    make: 'Makes something from a video: a GIF, a trim, a 9:16 copy, a loop, a poster frame.',
    captures: 'Lists your screenshots and recordings.',
    'capture-last': 'Opens your newest screenshot or recording.',
    annotate: 'Draws on a screenshot: arrows, boxes, text, blur.',
    editor: 'Opens the video editor on the open video (or a new edit).',
    intro: 'Plans and builds a motion-design video for socials with the chats, step by step.',
    cut: 'Turns clip editing on or off for the open video.',
    transition: 'Adds a transition into the selected clip (dissolve, wipe, glitch…).',
    'add-title': 'Adds a title over the picture at the playhead.',
    keyframe: 'Adds a keyframe at the playhead on the selected clip.',
    'edit-render': 'Renders the edit for a social format, a small file, a GIF or stills.',
    clip: 'Selects a clip by its number.',
    play: 'Plays the open video (or the song in the Lab, the clips on the board).',
    pause: 'Pauses the open video (or the song, the clips on the board).',
    // the app
    settings: 'Opens Settings.',
    theme: 'Switches the app\'s look (Forgeheart, Classic, Chrome Forge, Molten…).',
    usage: 'Opens the token and usage dashboard.',
    flows: 'Opens the Commands page on the flows: step lists like Doctor, Make a video, Record.',
    flow: 'Starts a flow (a list of steps) in this chat.',
    every: 'Runs a command again and again on a timer.',
    after: 'Runs a command once after a delay.',
    at: 'Runs a command once at a time of day.',
    repeat: 'Runs the last command (or one you name) again, N times.',
    run: 'Runs several commands in a row.',
    macro: 'Records the commands you run into your own command.',
    alias: 'Makes your own command name for a command line.',
    timers: 'Lists your command timers with buttons to stop them.',
    calc: 'Does quick math without sending anything.',
    keys: 'Lists commands that also have a keyboard shortcut.',
    calm: 'Tucks secondary buttons away (on) or shows everything (off).',
    customise: 'Shows what waits behind Alt or hover and what you pinned on screen.',
    meter: 'Shows the token meter as a strip, a pill, or hides it.',
    budget: 'Sets a daily token budget for an agent.',
    backup: 'Backs Hearth up now (or lists your backups).',
    sync: 'Syncs Hearth with your cloud drive between the Mac and the PC.',
    appearance: 'Opens the Appearance picker (presets, textures, glow, motion).',
    accent: 'Sets your own accent color.',
    classic: 'Switches to the original Forgeheart Classic look.',
    zen: 'Hides the message buttons until you point at them.',
    zoom: 'Changes the chat text size.',
    notes: 'Opens Notes.',
    prompts: 'Opens your saved prompts.',
    palette: 'Opens the command palette (Ctrl/⌘+K).',
    commands: 'Opens this page: every command explained and run input by input.',
  };

  // what / when for the principal commands (the "/" menu)
  const ABOUT = {
    help: ['Lists every command with its examples and keys, searchable.', 'When you don\'t remember a name: this page does the same with previews and one question at a time.'],
    new: ['Opens a new, empty chat with the agent you are on; anything you write after it becomes the first message.', 'When you change subject: a fresh chat keeps replies cheaper and focused.'],
    compact: ['Asks the agent to fold the conversation so far into a summary it carries on from. Every message stays in the chat.', 'When a long chat gets slow or the meter shows big context costs.'],
    stop: ['Stops the reply in progress, keeping what was written so far.', 'When a reply goes off track or takes too long.'],
    retry: ['Throws away the last reply and asks again, optionally with another model.', 'When the answer missed the point or you want to compare models.'],
    copy: ['Copies the last reply, its code block, one message, your own messages or the whole chat.', 'To paste a reply into another app.'],
    read: ['Reads a reply aloud with the system voice; you can change the speed or the voice.', 'When you are away from the screen or want to listen while you work.'],
    undo: ['Takes back the last action of the place you are in: a chat action, an editor edit, a board move.', 'Right after a mistake.'],
    screenshot: ['Takes a picture of the window (or only the Lab) and puts it in your message.', 'To show the agent what you see.'],
    do: ['Finds an action from the Ctrl/⌘+K palette by name and runs it.', 'For the app\'s own buttons that have no command of their own.'],
    astra: ['Sends your words to Astra\'s open chat without leaving where you are.', 'For a quick question to ChatGPT while you work with Claude.'],
    claude: ['Sends your words to Claude\'s open chat without leaving where you are.', 'For a quick question to Claude while you are elsewhere.'],
    handoff: ['The other agent continues this chat from a short summary (or the last messages).', 'When one agent is stuck, slow, or out of budget.'],
    jam: ['Claude and Astra take turns improving a music visual in the Lab, one round each; you keep the best round.', 'When you want ideas you wouldn\'t have tried yourself.'],
    opinion: ['The other agent reads the last reply and says what it would change.', 'Before you trust an important answer.'],
    decide: ['Astra picks a look, an effect, a palette, the frame size or the app look for you, with Undo.', 'When you don\'t want to choose.'],
    doctor: ['Checks every copy of Claude Code and Codex: versions, signed in, too old, with fixes in a window you can see.', 'When an agent doesn\'t answer or says it is too old.'],
    'save-sliders': ['Writes the current slider values into the selected layer\'s code, so they become the new defaults.', 'When the picture looks right: you did this 46 times in a day and a half.'],
    shuffle: ['Gives the sliders new random values: all of them or a group, gently or wildly, from a seed you can come back to.', 'To explore looks fast; Shift+R goes back, Save keeps one.'],
    tap: ['Tap along with the beat to set the tempo, or give the BPM; "one" sets the downbeat.', 'When the detected tempo is off.'],
    freeze: ['Holds the picture still while the music keeps playing; again to unfreeze. "beat" or "bar" freezes exactly on the next one.', 'To look at a frame, take a still, or make a hard cut on the beat.'],
    size: ['Sets the Lab picture to an exact social frame: 9:16, 16:9, 4:5, 1:1 (or fit the preview).', 'Before a still, a recording or a render for one platform.'],
    live: ['Makes the scene react to live sound: the computer\'s sound (Spotify, YouTube…), the microphone, or off; gain and latency too.', 'To jam along to music that isn\'t loaded as a song.'],
    present: ['Shows only the preview, fullscreen.', 'To watch the piece or show it to someone.'],
    sketches: ['Lists your sketches, newest first, or browses them as pictures.', 'To get back to an older scene.'],
    scene: ['Shows the Lab scene this director chat owns, links the open one, or makes a fresh one.', 'When a chat should work on another scene.'],
    look: ['Outside the Lab: the Appearance picker. In the Lab: switches between your saved slider looks.', 'To change the mood quickly.'],
    still: ['Saves a picture at the exact frame size (or copies it).', 'For a cover, a post, or to show an agent.'],
    sequence: ['Shows the Lab sequence: your scenes, footage, titles and the song on one timeline, played in the preview.', 'When you go from one scene to a whole video.'],
    board: ['Opens the mood board: websites, pictures and clips you collect for a vibe.', 'When you gather references.'],
    'board-use': ['Gives your next message the board\'s vibe (palette, light, motion, mood words), never the media itself.', 'When a chat should make something in the mood of your references.'],
    capture: ['The capture menu: screenshots and recordings of Hearth, tours, the frame reader.', 'For your intro video or to show a bug.'],
    rec: ['Records Hearth itself (window, tool, chat or a region), with a countdown and optional sound.', 'To film the app for socials.'],
    editor: ['Opens the video editor: tracks, cuts, titles, transitions, frame-exact stepping, render.', 'To finish a video.'],
    intro: ['Plans a short social video with the chats and builds it step by step: vibe, Lab scenes, captures, edit, every format.', 'When you want a finished motion-design video, not only a scene.'],
    settings: ['Opens Settings.', 'For engines, paths, sync, recording and look options.'],
    theme: ['Switches the app\'s look (Forgeheart, Classic, Chrome Forge, Molten…).', 'When you want the app to feel different.'],
    usage: ['Opens the usage dashboard: tokens per agent, model, tool and chat, budgets, export.', 'To see what costs the most.'],
    flows: ['Opens this page on the flows: lists of steps like Doctor or Make a video.', 'For longer tasks you walk through.'],
    flow: ['Starts a flow (a list of steps) in this chat; its card shows where it is.', 'For a guided task the chat can follow too.'],
  };

  // explicit questions (where the args string isn't enough)
  const Y = (label = 'Yes', value = 'on') => o(label, value);
  const Q = {
    size: { q: [{ title: 'Which frame size?', kind: 'choice', required: true, options: SIZES, free: true, placeholder: 'or 21:9, 4k, tiktok…' }], repeat: false },
    still: { q: [{ title: 'Optional: which size?', kind: 'choice', options: SIZES.slice(0, 4) }, { title: 'Copy it to the clipboard too?', kind: 'yesno', options: [o('Yes, copy it', 'copy'), o('No', '')] }], repeat: 'every' },
    shuffle: { q: [{ title: 'Optional: what to shuffle?', kind: 'choice', options: [o('Everything', ''), o('Colors only', 'colors'), o('Numbers only', 'numbers'), o('My favourite sliders', 'favs')], fromComplete: true, free: true },
      { title: 'Optional: how far?', kind: 'choice', options: [o('Subtle', 'subtle'), o('Normal', 'normal'), o('Bold', 'bold'), o('Wild', 'wild')] }], repeat: 'every' },
    freeze: { q: [{ title: 'Optional: when?', kind: 'choice', options: [o('Now (toggle)', ''), o('On the next beat', 'beat'), o('On the next bar', 'bar'), o('Unfreeze', 'off')] }], repeat: false },
    live: { q: [{ title: 'Which sound should the scene hear?', kind: 'choice', required: true, options: [o('The computer\'s sound (Spotify, YouTube…)', 'system'), o('The microphone', 'mic'), o('Turn it off', 'off'), o('Calibrate the latency from my taps', 'calibrate')] }], repeat: false },
    tap: { q: [{ title: 'Optional: a tempo?', kind: 'count', options: [o('120'), o('128'), o('140'), o('The downbeat is here', 'one')], free: true, placeholder: 'BPM, e.g. 124' }], repeat: 'count' },
    sequence: { q: [{ title: 'Optional: what to do with it?', kind: 'choice', options: [o('Show / hide it', ''), o('Add this scene', 'add'), o('Add a title', 'title'), o('Render it', 'render'), o('Finish it in the editor', 'editor')] }], repeat: false },
    scene: { q: [{ title: 'Optional: what about the scene?', kind: 'choice', options: [o('Show which scene this chat owns', ''), o('Link the open sketch to this chat', 'link'), o('A fresh scene', 'new'), o('Unlink it', 'unlink')] }], repeat: false },
    look: { q: [{ title: 'Optional: which look?', kind: 'choice', options: [o('Open the picker', ''), o('The next one', 'next'), o('A random one', 'random'), o('Save the current one…', 'save', 'then a name')], fromComplete: true, free: true }], repeat: 'every' },
    theme: { q: [{ title: 'Which look for the app?', kind: 'choice', required: true, options: [o('The next one', 'next'), o('A random one', 'random')], fromComplete: true, free: true }], repeat: 'every' },
    board: { q: [{ title: 'Optional: which board?', kind: 'text', fromComplete: true, placeholder: 'the board\'s name (empty: the one you were on)' }], repeat: false },
    'board-use': { q: [{ title: 'Send it now, or with your next message?', kind: 'choice', options: [o('With my next message', ''), o('Send it now', 'send')] }], repeat: false },
    capture: { q: [{ title: 'Optional: what do you want to capture?', kind: 'choice', options: [o('Open the capture menu', ''), o('A screenshot', 'shot'), o('A recording', 'record'), o('A scripted tour', 'tour'), o('My captures', 'library'), o('Read frames of a video', 'frames')] }], repeat: false },
    rec: { q: [{ title: 'What do you want to record?', kind: 'choice', required: true, options: [o('The whole window', 'window'), o('This tool', 'tool'), o('The chat', 'chat'), o('A region I drag', 'region'), o('Stop the recording', 'stop')] },
      { title: 'Optional: sound?', kind: 'choice', options: [o('No sound', ''), o('Hearth\'s sound', 'sound'), o('The microphone', 'mic'), o('Both', 'both')] },
      { title: 'Optional: how long?', kind: 'choice', options: [o('Until I stop it', ''), o('10 seconds', '10s'), o('30 seconds', '30s')] }], repeat: false },
    record: { q: [{ title: 'What should it record?', kind: 'choice', required: true, options: [o('The loop', 'loop'), o('The whole song', 'song'), o('8 bars from here', '8 bars'), o('15 seconds', '15s'), o('From here until I stop', 'here'), o('Stop', 'stop')], free: true },
      { title: 'Optional: frame rate?', kind: 'choice', options: [o('30 fps', '30'), o('60 fps', '60')] }, { title: 'High quality?', kind: 'yesno', options: [o('Yes', 'hq'), o('No', '')] }], repeat: false },
    editor: { q: [{ title: 'Optional: open what?', kind: 'choice', options: [o('The open video', ''), o('A new edit…', 'new', 'then a name'), o('The list of edits', 'list'), o('Close the editor', 'off')] }], repeat: false },
    intro: { q: [{ title: 'What is the video about?', kind: 'text', required: true, placeholder: 'a 15 s teaser: two AIs, one window', options: [o('Build it now (the plan exists)', 'go'), o('Where is it?', 'status')] }], repeat: false },
    decide: { q: [{ title: 'What should Astra choose?', kind: 'choice', required: true, options: [o('A Lab look', 'look'), o('An effect', 'effect'), o('A palette', 'palette'), o('The frame size', 'size'), o('The app look', 'theme'), o('Undo its last pick', 'undo')] },
      { title: 'Optional: a goal in your words?', kind: 'text', placeholder: 'dreamy and calm' }], repeat: false },
    jam: { q: [{ title: 'Optional: what should they make?', kind: 'text', placeholder: 'an ember tunnel on the drop', options: [o('Stop the jam', 'stop'), o('Again', 'again'), o('Share it', 'share')] }], repeat: false },
    opinion: { q: [{ title: 'Optional: from whom?', kind: 'choice', options: [o('The other agent', ''), o('Claude', 'claude'), o('Astra', 'astra')] }], repeat: false },
    handoff: { q: [{ title: 'Optional: to whom?', kind: 'choice', options: [o('The other agent', ''), o('Claude', 'claude'), o('Astra', 'astra')] }, { title: 'Send the last messages as they are (no summary)?', kind: 'yesno', options: [o('Yes, raw', '--raw'), o('No, a summary', '')] }], repeat: false },
    new: { q: [{ title: 'Optional: the first message?', kind: 'text', placeholder: 'what the new chat is about' }], repeat: false },
    read: { q: [{ title: 'Optional: what to read?', kind: 'choice', options: [o('The last reply', ''), o('Stop reading', 'stop'), o('Read every new reply', 'auto on'), o('Stop reading new replies', 'auto off')] }], repeat: false },
    copy: { q: [{ title: 'Optional: copy what?', kind: 'choice', options: [o('The last reply', ''), o('Its code', 'code'), o('The whole chat', 'all'), o('Its thinking', 'thinking'), o('My messages', 'mine')] }], repeat: false },
    retry: { q: [{ title: 'Optional: with another model?', kind: 'text', fromComplete: true, placeholder: 'empty: the same model' }], repeat: false },
    screenshot: { q: [{ title: 'Optional: of what?', kind: 'choice', options: [o('The window', ''), o('The Lab only', 'lab')] }], repeat: 'every' },
    astra: { q: [{ title: 'What should Astra get?', kind: 'text', required: true, placeholder: 'your message' }], repeat: false },
    claude: { q: [{ title: 'What should Claude get?', kind: 'text', required: true, placeholder: 'your message' }], repeat: false },
    help: { q: [{ title: 'Optional: a word to look for?', kind: 'text', placeholder: 'lab, board, record…' }], repeat: false },
    usage: { q: [{ title: 'Optional: which part?', kind: 'text', fromComplete: true, placeholder: 'empty: the overview' }], repeat: false },
    doctor: { q: [{ title: 'Also test both with a real reply? (a few tokens)', kind: 'yesno', options: [o('Yes, test them', '--run'), o('No, just check', '')] }], repeat: false },
    sketches: { q: [{ title: 'As pictures?', kind: 'yesno', options: [o('Yes, browse them', 'browse'), o('No, a list', '')] }], repeat: false },
    'save-look': { q: [{ title: 'Optional: a name for the look?', kind: 'text', placeholder: 'empty: a quick name' }], repeat: false },
    slider: { q: [{ title: 'Which slider?', kind: 'text', required: true, fromComplete: true, placeholder: 'glow, tint, speed…' }, { title: 'Its new value?', kind: 'text', required: true, placeholder: '2.5, #ff3cac, on…' }], repeat: false },
    bpm: { q: [{ title: 'Which tempo?', kind: 'count', required: true, options: [o('Detected (auto)', 'auto'), o('Double it', 'x2'), o('Half', 'half'), o('120'), o('128')], free: true, placeholder: 'a BPM' }], repeat: false },
    loop: { q: [{ title: 'What should loop?', kind: 'choice', required: true, options: [o('4 bars from here', '4 bars'), o('8 bars from here', '8 bars'), o('This bar', 'bar'), o('Stop looping', 'off')], free: true, placeholder: '0:32 0:48' }], repeat: false },
    morph: { q: [{ title: 'How far between the two slots?', kind: 'choice', required: true, options: [o('Halfway', '50%'), o('All the way to the second', '1'), o('Back to the first', '0'), o('Glide while it plays (8 bars)', 'auto 8'), o('Stop gliding', 'off')], free: true }], repeat: false },
    'layer-add': { q: [{ title: 'Optional: which layer?', kind: 'text', fromComplete: true, placeholder: 'empty: browse them' }, { title: 'Above everything?', kind: 'yesno', options: [o('Yes, on top', '--above'), o('No, above the selected one', '')] }], repeat: false },
    fx: { q: [{ title: 'Optional: which effect?', kind: 'text', fromComplete: true, placeholder: 'empty: the picker' }, { title: 'Above every layer?', kind: 'yesno', options: [o('Yes', '--top'), o('No, above the selected one', '')] }], repeat: false },
    'follow-music': { q: [{ title: 'Which slider should move?', kind: 'text', required: true, fromComplete: true }, { title: 'With which part of the music?', kind: 'choice', required: true, options: ['kick', 'snare', 'hats', 'bass', 'mid', 'treble', 'level', 'beat', 'off'] }, { title: 'Optional: how much (−1…1)?', kind: 'count', options: ['0.25', '0.5', '1', '-0.5'] }], repeat: false },
    every: { q: [{ title: 'How often?', kind: 'count', required: true, options: [o('Every 30 seconds', '30s'), o('Every minute', '1m'), o('Every 5 minutes', '5m'), o('Every 8 bars', '8 bars')], free: true }, { title: 'Which command?', kind: 'command', required: true, placeholder: '/shuffle colors' }], repeat: false },
    after: { q: [{ title: 'After how long?', kind: 'count', required: true, options: [o('30 seconds', '30s'), o('2 minutes', '2m'), o('10 minutes', '10m')], free: true }, { title: 'Which command?', kind: 'command', required: true, placeholder: '/freeze off' }], repeat: false },
    at: { q: [{ title: 'When?', kind: 'text', required: true, options: [o('In 10 minutes', 'in 10m'), o('In an hour', 'in 1h')], placeholder: '21:30, 9pm' }, { title: 'Which command?', kind: 'command', required: true }], repeat: false },
    repeat: { q: [{ title: 'How many times?', kind: 'count', required: true, options: ['2', '3', '5', '10'], free: true }, { title: 'Optional: which command? (empty: the last one)', kind: 'command' }], repeat: false },
    run: { q: [{ title: 'Which commands, in order?', kind: 'command', required: true, placeholder: '/size 9:16 ; /freeze ; /still' }], repeat: false },
    remember: { q: [{ title: 'What should it remember?', kind: 'text', required: true, placeholder: 'I edit on a Mac, 9:16 first' }], repeat: false },
    forget: { q: [{ title: 'Forget facts with which words?', kind: 'text', required: true, options: [o('The newest fact', 'last')] }], repeat: false },
    summarize: { q: [{ title: 'Optional: how long?', kind: 'choice', options: [o('Normal', ''), o('Short', 'short'), o('Long', 'long'), o('5 bullets', '5 bullets')] }], repeat: false },
    persona: { q: [{ title: 'Which role?', kind: 'text', required: true, fromComplete: true, options: [o('Back to normal', 'off')] }], repeat: false },
    tone: { q: [{ title: 'Which tone?', kind: 'text', required: true, fromComplete: true, options: [o('Back to normal', 'off')] }], repeat: false },
    model: { q: [{ title: 'Optional: which model?', kind: 'text', fromComplete: true, options: [o('The default', 'default')], placeholder: 'empty: show the one in use' }], repeat: false },
    effort: { q: [{ title: 'How hard should it think?', kind: 'choice', required: true, options: [o('Low (fast, cheap)', 'low'), o('Medium', 'medium'), o('High', 'high'), o('Extra high (slow, more tokens)', 'xhigh')] }], repeat: false },
    duo: { q: [{ title: 'What should both answer?', kind: 'text', required: true }], repeat: false },
    debate: { q: [{ title: 'What should they debate?', kind: 'text', required: true }], repeat: false },
    relay: { q: [{ title: 'What should they work on?', kind: 'text', required: true }], repeat: false },
    tour: { q: [{ title: 'Optional: which tour?', kind: 'text', fromComplete: true, options: [o('Pick from the list', ''), o('Stop the tour', 'stop')] }], repeat: false },
    frames: { q: [{ title: 'Which video?', kind: 'choice', required: true, options: [o('My newest capture', 'last'), o('The open video', 'video'), o('Choose a file…', 'open')] },
      { title: 'What should it read?', kind: 'choice', required: true, options: [o('A contact sheet', 'sheet'), o('Scene changes', 'scenes'), o('The pacing', 'pacing'), o('The palette', 'palette'), o('A frame at a time…', 'at', 'then a time')], free: true }], repeat: false },
    make: { q: [{ title: 'Make what?', kind: 'choice', required: true, options: [o('A GIF', 'gif'), o('A 9:16 copy', '9:16'), o('A seamless loop', 'loop'), o('A poster frame', 'poster'), o('A boomerang', 'boomerang'), o('A timelapse', 'timelapse')], fromComplete: true },
      { title: 'From which video?', kind: 'choice', options: [o('My newest capture', 'last'), o('The open video', 'video'), o('Choose a file…', 'open')] }], repeat: false },
    transition: { q: [{ title: 'Which transition?', kind: 'choice', required: true, options: ['dissolve', 'dip-black', 'wipe-left', 'push-up', 'zoom-in', 'whip-left', 'glitch', o('Remove it', 'off')], fromComplete: true, free: true }, { title: 'Optional: how long (seconds)?', kind: 'count', options: ['0.3', '0.5', '1'] }], repeat: false },
    'add-title': { q: [{ title: 'What should the title say?', kind: 'text', required: true }], repeat: false },
    'edit-render': { q: [{ title: 'Optional: for what?', kind: 'text', fromComplete: true, options: [o('A new version', ''), o('Reels / TikTok', 'reels'), o('YouTube 1080p', 'yt1080'), o('A GIF', 'gif')] }], repeat: false },
    'board-add': { q: [{ title: 'What should go on the board?', kind: 'text', required: true, placeholder: 'a website, a file path, #ff3cac #2a1b3d, or a note' }], repeat: false },
    'board-new': { q: [{ title: 'A name for the board?', kind: 'text', required: true, placeholder: 'night refs' }], repeat: false },
    'board-layout': { q: [{ title: 'Which layout?', kind: 'choice', required: true, options: ['grid', 'masonry', 'timeline', 'collage', 'rainbow'], fromComplete: true }], repeat: false },
    vibe: { q: [{ title: 'Optional: the vibe of what?', kind: 'choice', options: [o('The whole board', ''), o('The selection', 'sel')], free: true }], repeat: false },
    accent: { q: [{ title: 'Which color?', kind: 'text', required: true, options: [o('Ember', 'ember'), o('Violet', 'violet'), o('Mint', 'mint'), o('Back to gold', 'reset')], placeholder: '#ffb000' }], repeat: false },
    zoom: { q: [{ title: 'Text size?', kind: 'choice', required: true, options: [o('Bigger', '+'), o('Smaller', '-'), o('Normal', '0'), o('110%', '110%'), o('125%', '125%')] }], repeat: false },
    backup: { q: [{ title: 'Optional: what?', kind: 'choice', options: [o('Back up now', 'now'), o('List my backups', 'list')] }], repeat: 'every' },
    export: { q: [{ title: 'Which format?', kind: 'choice', options: [o('Markdown', 'md'), o('HTML', 'html'), o('JSON', 'json'), o('Text', 'txt')] }, { title: 'Where?', kind: 'choice', options: [o('A file', 'file'), o('The clipboard', 'clipboard')] }], repeat: false },
    flow: { q: [{ title: 'Which flow?', kind: 'text', required: true, fromComplete: true }], repeat: false },
    commands: { q: [{ title: 'Optional: open it on which command?', kind: 'command' }], repeat: false },
  };
  for (const v of Object.values(Q)) for (const q of v.q) q.options = (q.options || []).map((x) => (typeof x === 'string' ? o(x) : x));

  // ---------- previews: one little scene per kind of action ----------
  // Matched in order on the command name (re) and / or its area; the first that fits. Colors by area.
  const SCENES = [
    ['frame', /^(size|fit|aspect|crop|edit-format|window-size|safe|guides|still|stills)$/],
    ['rec', /^(rec|record|record-presets|capture-tools|film|loop-frames)$|record/],
    ['shot', /^(shot|screenshot|grab|copy-shot|crop-shot|beautify|annotate|attach-screen|attach-region|forge-shot|board-screenshot|contact-sheet|contact|sheet|poster-frame)$/],
    ['freeze', /^(freeze|freeze-frame|hold-frame|pause|stop|stop-all|blackout)$/],
    ['beat', /^(tap|bpm|kick|snare|hit|marker|downbeat|beat-grid|mark-kicks|quantize|nudge-grid|click-track|tap-latency|analyze|drops|sections|cue|cues|follow-music|make-it-react|live|live-status|triggers|trigger-preset|auto-preset|autobars|beat-markers|kit-bpm|midi-learn)$/],
    ['sliders', /^(shuffle|reshuffle|unshuffle|shuffle-mode|shuffle-pick|slider|sliders|slider-group|knob|tame|exaggerate|reset-sliders|undo-sliders|save-sliders|save-one|copy-sliders|paste-sliders|lock-slider|unlock-slider|fav-slider|move-slider|find-slider|morph|slot|surprise|tweak-code)$/],
    ['grid', /^board-(align|distribute|grid|layout|gather|untangle|snap|arrange|template|starter)$|^(arrange|board-layout)$/],
    ['board', /^(board|boards|board-|ref$|vibe$)/],
    ['timeline', /^(editor|cut|clip|clips|trim|razor|ripple|roll|slip|slide|lift|insert|overwrite|nest|unnest|track|transition|split|sequence|add-scene|scene-timeline|footage|lab-cuts|cut-|edit-|keyframe|speed-ramp|move-clip|dup-clip|swap|fill-slot|fit-to-fill|song-trim|send-clip|lab-to-editor|extend-edit|range-selection|select|lane-height|shuffle-clips|to-main|to-overlay|copy-clips|paste-clips|copy-keyframes|paste-keyframes|keyframes|sequences|sequence-)/],
    ['frames', /^(frames|frame-|next-frame|goto-frame|step|shuttle|onion|frame-at|frame-palette|pacing|pace-check|match-pacing|scenes|ref-frames|motion-curve|extract|match-frame)/],
    ['play', /^(play|present|fullscreen|board-present|board-play|present-|stage-window|lab-focus|focus|zen|board-present-auto)$/],
    ['layers', /^(layer|layer-add|fx|fx-list|fx-picker|fx-palette|blend|blend-mode|overlay|lab-overlay|comp|dispatch|effect|adjust|grade|scopes|mirror|reverse|pingpong)$/],
    ['palette', /^(theme|themes|look|looks|look-apply|save-look|appearance|accent|classic|texture|glow|sparkles|motion|corners|density|palette$|lab-palette|recolor|color|colors|gradient|harmony|contrast|kit-palette|save-palette|board-palette|board-harmony|board-color|board-eyedropper|brand-look|match-look|chatfont|font)$/],
    ['motion', /^(motion-|kinetic|camera-move|logo-reveal|end-card|hearth-on-screen|hearth-ui|type-3d|animate|ease|easing|cursor-path|shot-list|ref-motion|title-card|add-title|lower-third|motion$)/],
    ['nodes', /^(nodes|shader-nodes|code-nodes|video-nodes|flow|flows|pipeline|video-flow)/],
    ['duo', /^(duo|relay|debate|council|collab|pair|merge|compare-agents|critique|redteam|factcheck|brainstorm|pick|handoff|opinion|jam|ask-astra|ask-claude|redo-with|continue-with|both|all|director-engine|duo-last|opinion-auto|collab-)/],
    ['meter', /^(usage|tokens|meter|meter-field|budget|budgets|budget-left|budget-warn|by-agent|by-tool|cache|chat-tokens|clicks|cold|hot|compare|context|cost-free|daily|estimate|export-usage|feature|features|forecast|hourly|last-reply|lifetime|long-warn|models|panel-totals|peak|replies|session|speed|split|stats|stats-|streak|streaming|top-chats|top-features|unused|usage-|weekdays|calibration|alerts|areas|badges|director-cost|director-stats|memory-cost|cmd-stats|astra-tokens|astra-usage)/],
    ['timer', /^(every|after|at|timers|timer-cancel|timers-pause|remind|wait|time|tc|timecode|chime)$/],
    ['undo', /^(undo|redo|undo-edit|redo-edit|restore|unarchive|trash|deleted|delete|archive|forget|clear-draft|clear-notes|nodes-undo|shader-nodes-undo|board-undo|board-redo|undo-report|cut-restore|restore-backup|cmd-reset|reset-transform|keyframes-clear|markers-clear|clear-markers)$/],
    ['save', /^(save|backup|backups|export|export-all|note-export|prompt-export|memory-export|cmd-export|collab-export|captions-export|cut-export|cut-export-all|download|downloads|render|edit-render|sequence-render|render-again|make|copy|copy-image|board-export|board-copy-image|post-text|cut-downs|sync)$/],
    ['search', /^(help|find|search|what|where|how|discover|list|keys|shortcuts|flow-where|flow-status|lab-state|status|info|doctor|astra-doctor|engines|check|why|recent|links|files|things|chat-context|captures|capture-last|videos|sketches|cues|markers|board-search|board-info|notes-find|note-find|memory-list|prompt-list|nodes-list|nodes-types|shader-nodes-list|shader-nodes-types|board-list|fx-list|motion-list|astra-status|astra-help|capture-help|video-status|forge-status|director-activity|director-peek|director-edits|task|principal)$/],
    ['doc', /^(note|notes|note-|daily-note|inbox|todo|library|prompt|prompts|prompt-|memory|remember|remember-all|memory-|draft|drafts|snippet|snippets|template|alias|unalias|macro|summarize|tldr|bullets|as-table|steps|pros-cons|examples|code-outline|captions-import|edit-edl|edit-list|board-note|board-text|board-brief|lab-note|forge-devlog)/],
    ['gear', /^(settings|customise|calm|reveal|rightclick|pin-control|unpin-control|tucked|ontop|notify|enter-sends|spell|engine-update|login|astra-login|effort|model|astra-|director-|dock|dock-|agent|agents|agent-new|agent-presets|ffmpeg|proxy|capture-folder|video-folders|cmdbar|cmd-|lab-tools|lab-keys|video-keys|fps|edit-fps|keys-overlay|cursor-fx|clean-ui|record-presets|presets|edit-presets|formats)/],
    ['forge', /^forge/],
    ['chat', /./],
  ];
  const AREA_COLOR = {
    'Three.js Lab': '#bd8bff', Video: '#48ddff', 'Video project': '#48ddff', Board: '#e6b450', Capture: '#ff5f6d', Collab: '#7cd992', Astra: '#7cd992', Agents: '#ffd75e',
    Chat: '#ffb15e', Messages: '#ffb15e', Compose: '#ffb15e', Style: '#ff8fc8', Memory: '#ff8fc8', Look: '#ff6b9d', View: '#ff6b9d', Meter: '#8fd3ff', App: '#c9b79c',
    Flows: '#ffd75e', Commands: '#ffd75e', Nodes: '#48ddff', 'Shader nodes': '#48ddff', Forge: '#ff8c42', Kit: '#ff6b9d', Notes: '#c9b79c', Prompts: '#c9b79c', Data: '#c9b79c',
    Export: '#c9b79c', Assist: '#7cd992', Director: '#bd8bff',
  };
  const AREA_ICON = { 'Three.js Lab': '◭', Video: '✂', 'Video project': '🎬', Board: '▦', Capture: '◉', Collab: '⚇', Astra: '✧', Agents: '☉', Chat: '☰', Messages: '✉', Compose: '✎', Style: '✎', Memory: '✱', Look: '◐', View: '◐', Meter: '▮', App: '⚙', Flows: '⇢', Nodes: '⊶', 'Shader nodes': '⊶', Forge: '⚒', Kit: '◍', Notes: '✎', Prompts: '✎', Data: '⛁', Export: '⇪', Assist: '✦', Director: '◈' };
  function sceneFor(def) {
    const name = String(def?.name || '');
    for (const [kind, re] of SCENES) if (re.test(name)) return kind;
    return 'chat';
  }
  // the parameters of a command's preview: its scene, color, icon, a short label
  function previewOf(def) {
    const kind = sceneFor(def);
    const label = (Q[def.name]?.q?.[0]?.options?.[0]?.value || String(def.args || '').replace(/[<>[\]]/g, '').split(/[\s|]+/)[0] || def.name).toString().slice(0, 8);
    return { kind, color: AREA_COLOR[def.area] || '#ffd75e', icon: AREA_ICON[def.area] || '/', label, seed: [...name(def)].reduce((a, c) => (a * 31 + c.charCodeAt(0)) >>> 0, 7) };
  }
  const name = (d) => String(d?.name || 'x');

  return { DESC, ABOUT, Q, SCENES, AREA_COLOR, AREA_ICON, sceneFor, previewOf, SIZES };
})();
if (typeof module !== 'undefined') module.exports = CmdPageData;
