// Commands page clips (round 11): real recorded mini clips of Hearth doing the principal commands, made by
// dev/make-command-clips.js (which rewrites this file). A command without a clip uses its SVG preview.
const CmdClips = {
  "astra": "assets/cmd-clips/astra.mp4",
  "board": "assets/cmd-clips/board.mp4",
  "board-use": "assets/cmd-clips/board-use.mp4",
  "capture": "assets/cmd-clips/capture.mp4",
  "claude": "assets/cmd-clips/claude.mp4",
  "commands": "assets/cmd-clips/commands.mp4",
  "compact": "assets/cmd-clips/compact.mp4",
  "copy": "assets/cmd-clips/copy.mp4",
  "decide": "assets/cmd-clips/decide.mp4",
  "do": "assets/cmd-clips/do.mp4",
  "doctor": "assets/cmd-clips/doctor.mp4",
  "editor": "assets/cmd-clips/editor.mp4",
  "flow": "assets/cmd-clips/flow.mp4",
  "flows": "assets/cmd-clips/flows.mp4",
  "freeze": "assets/cmd-clips/freeze.mp4",
  "handoff": "assets/cmd-clips/handoff.mp4",
  "help": "assets/cmd-clips/help.mp4",
  "intro": "assets/cmd-clips/intro.mp4",
  "jam": "assets/cmd-clips/jam.mp4",
  "new": "assets/cmd-clips/new.mp4",
  "opinion": "assets/cmd-clips/opinion.mp4",
  "present": "assets/cmd-clips/present.mp4",
  "read": "assets/cmd-clips/read.mp4",
  "rec": "assets/cmd-clips/rec.mp4",
  "retry": "assets/cmd-clips/retry.mp4",
  "save-sliders": "assets/cmd-clips/save-sliders.mp4",
  "screenshot": "assets/cmd-clips/screenshot.mp4",
  "sequence": "assets/cmd-clips/sequence.mp4",
  "settings": "assets/cmd-clips/settings.mp4",
  "shuffle": "assets/cmd-clips/shuffle.mp4",
  "size": "assets/cmd-clips/size.mp4",
  "stop": "assets/cmd-clips/stop.mp4",
  "theme": "assets/cmd-clips/theme.mp4",
  "undo": "assets/cmd-clips/undo.mp4",
  "usage": "assets/cmd-clips/usage.mp4"
};
