const { contextBridge, ipcRenderer, webFrame, webUtils } = require('electron');

const on = (channel) => (cb) => ipcRenderer.on(channel, (_e, data) => cb(data));
const call = (channel) => (...args) => ipcRenderer.invoke(channel, ...args);

contextBridge.exposeInMainWorld('hub', {
  getConfig: call('config:get'),
  saveConfig: call('config:save'),
  onConfigChanged: on('config:changed'),
  onShortcut: on('shortcut'),
  openFile: call('open-file'),
  openExternal: call('open-external'),
  openDataFolder: call('open-data-folder'),

  listChats: call('chats:list'),
  getChat: call('chats:get'),
  saveChat: call('chats:save'),
  deleteChat: call('chats:delete'),
  searchChatText: call('chats:searchText'),
  listChatTrash: call('chats:trash'),
  restoreChat: call('chats:restore'),
  importChats: call('chats:import'), // (opts?: { path, dryRun }) → summary; no path opens a file dialog
  onImportProgress: on('import:progress'),
  backup: { now: call('backup:now'), list: call('backup:list'), dir: call('backup:dir'), pick: call('backup:pick'), restore: call('backup:restore') },
  pickFolder: call('pick-folder'),
  getMemory: call('memory:get'),
  saveMemory: call('memory:save'),
  getConnectors: call('connectors:get'),
  refreshConnectors: call('connectors:refresh'),
  getHistory: call('history:get'),
  saveHistory: call('history:save'),
  kvGet: call('kv:get'),
  kvSet: call('kv:set'),
  saveAttachment: call('attachments:save'),
  importRef: call('refs:import'),
  attachmentsDir: call('attachments:dir'),
  getUsage: call('usage:get'),
  getTokenStats: call('usage:stats'),
  rebuildTokenStats: call('usage:rebuild'),

  send: call('engine:send'),
  stop: call('engine:stop'),
  stopAll: call('engine:stopAll'),
  login: call('engine:login'),
  engineStatus: call('engine:status'),
  engineDoctor: call('engine:doctor'),
  engineInstalls: call('engine:installs'),
  engineFix: call('engine:fix'),
  ffmpegStatus: call('tools:ffmpeg'),
  ffmpegInstall: call('tools:installFfmpeg'),
  onEngineInstalls: on('engine:installs'),
  onEngineEvent: on('engine:event'),

  // window & desktop
  showWindow: call('window:show'),
  flashWindow: call('window:flash'),
  isWindowFocused: call('window:isFocused'),
  reloadWindow: call('window:reload'),
  onWindowFocus: on('window:focus'),
  findStart: call('find:start'),
  findStop: call('find:stop'),
  onFindResult: on('find:result'),
  createShortcuts: call('shortcuts:create'),
  restartApp: call('app:restart'),
  askOnce: call('engine:once'),
  captureWindow: call('window:capture'),
  setOnTop: call('window:onTop'),
  exportData: call('data:export'),
  packForMac: call('data:packForMac'),
  platform: call('app:platform'),
  liveStart: call('live:start'),
  npStart: call('np:start'),
  npStop: call('np:stop'),
  npControl: call('np:control'),
  onNowPlaying: on('np:update'),
  stageOpen: call('stage:open'),
  stageOnTop: call('stage:onTop'),
  stageClose: call('stage:close'),
  stageFocus: call('stage:focus'),
  stageSend: (msg) => ipcRenderer.send('stage:to', msg),
  onStageMessage: on('stage:from'),
  onStageClosed: on('stage:closed'),
  setZoom: (factor) => webFrame.setZoomFactor(factor),
  getZoom: () => webFrame.getZoomFactor(),
  pathForFile: (file) => webUtils.getPathForFile(file),
  onTray: (cb) => {
    ipcRenderer.on('tray:new-chat', () => cb('new-chat'));
    ipcRenderer.on('tray:palette', () => cb('palette'));
  },
  onContextAction: (cb) => {
    ipcRenderer.on('context:ask', (_e, text) => cb('ask', text));
    ipcRenderer.on('context:note', (_e, text) => cb('note', text));
  },
  onDownload: on('download:update'),
  onGameCall: on('game:call'),
  gameResult: (id, result) => ipcRenderer.invoke('game:result', id, result),
  directorCost: call('director:cost'), // (agents?) → per-message cost of each director's tools (mcp/cost.js)
  directorGuide: call('director:guide'), // (topic) → the Three Director's guide text for that topic

  // files & tools
  fs: {
    list: call('fs:list'),
    read: call('fs:read'),
    write: call('fs:write'),
    stat: call('fs:stat'),
    search: call('fs:search'),
    trash: call('fs:trash'),
    zip: call('fs:zip'),
    diff: call('fs:diff'),
    reveal: call('fs:reveal'),
    open: call('fs:open'),
    copy: call('fs:copy'),
    watch: call('fs:watch'),
    unwatch: call('fs:unwatch'),
    home: call('fs:home'),
    onChanged: on('fs:changed'),
  },
  chatMedia: { find: call('chatmedia:find') },
  fetchText: call('net:text'),
  openDialog: call('dialog:open'),
  saveFile: call('dialog:saveFile'),
  // mood board (boardmain.js): copies into data/board/media, page pictures, website snapshots
  board: { dir: call('board:dir'), import: call('board:import'), save: call('board:save'), fetch: call('board:fetch'), snap: call('board:snap'), unused: call('board:unused') },
  ae: {
    status: call('ae:status'),
    templates: call('ae:templates'),
    run: call('ae:run'),
    install: call('ae:install'),
    projects: call('ae:projects'),
    render: call('ae:render'),
    cancel: call('ae:cancel'),
    onRender: on('ae:render-event'),
    running: call('ae:running'),
  },
  // Capture (capturemain.js): screenshots / recordings of Hearth itself, the exact frame reader
  capture: {
    dir: call('capture:dir'),
    shot: call('capture:shot'),
    save: call('capture:save'),
    list: call('capture:list'),
    copyImage: call('capture:copyImage'),
    trash: call('capture:trash'),
    prep: call('capture:prep'),
    recOpen: call('capture:recOpen'),
    recWrite: call('capture:recWrite'),
    recClose: call('capture:recClose'),
    finish: call('capture:finish'),
    indicator: call('capture:indicator'),
    frames: call('capture:frames'),
    edit: call('capture:edit'),
    windowSize: call('capture:windowSize'),
    startDrag: (p) => ipcRenderer.send('capture:drag', p),
    onKey: on('capture:key'),
    onIndicator: on('capture:indicator'),
    onProgress: on('capture:progress'),
  },
  // Sync through a cloud drive folder (syncmain.js)
  sync: {
    status: call('sync:status'), detect: call('sync:detect'), on: call('sync:on'), off: call('sync:off'), now: call('sync:now'),
    pause: call('sync:pause'), big: call('sync:big'), conflicts: call('sync:conflicts'), resolve: call('sync:resolve'),
    trash: call('sync:trash'), restore: call('sync:restore'), open: call('sync:open'), download: call('sync:download'), ack: call('sync:ack'),
    onStatus: on('sync:status'), onPulled: on('sync:pulled'),
  },
  video: {
    tools: call('video:tools'),
    probe: call('video:probe'),
    transcode: call('video:transcode'),
    cancel: call('video:cancel'),
    rmtemp: call('video:rmtemp'),
    onJob: on('video:job-event'),
  },
  // The render queue (rendersmain.js): run / pause / resume / cancel a queued ffmpeg job, encoders of this ffmpeg
  renders: { run: call('renders:run'), pause: call('renders:pause'), resume: call('renders:resume'), cancel: call('renders:cancel'), relay: call('renders:relay'), encoders: call('renders:encoders') },
});
