// Built-in prompt presets for the prompt library (notes.js → Prompts). Each is [category, name, text].
// Blanks: {{name}} (empty), {{name=default text}} (prefilled) or {{name|a,b,c}} (a dropdown, first is the default).
// They're merged into your saved prompts at load and never overwrite yours: editing one saves your own copy,
// deleting one hides it. New presets added here show up automatically.
const PromptLibrary = (() => {
  const CATS = {
    coding: 'Coding', three: 'Three.js & shaders', music: 'Music visuals', ae: 'After Effects', game: 'Game dev & Forgeheart',
    writing: 'Writing', social: 'Social posts & captions', review: 'Review & critique', plan: 'Planning', learn: 'Learning', basics: 'Everyday',
  };
  const P = [
    // ---------- coding ----------
    ['coding', 'Explain this code', 'Explain what this code does, step by step, and point out anything risky:\n\n```\n{{code}}\n```'],
    ['coding', 'Fix this bug', 'This code has a bug: {{symptom}}\n\n```\n{{code}}\n```\n\nFind the cause and give me the corrected code.'],
    ['coding', 'Refactor for readability', 'Refactor this {{language=JavaScript}} code for readability without changing behavior. Keep the same public names. Show the result, then list what you changed in one line each.\n\n```\n{{code}}\n```'],
    ['coding', 'Write tests', 'Write {{style|small plain asserts,Jest,Vitest,node:test}} tests for this code. Cover the normal path, edge cases and one failure case.\n\n```\n{{code}}\n```'],
    ['coding', 'Add error handling', 'Add sensible error handling to this code: validate inputs, catch failures where they can happen, and give clear messages. Don\'t over-engineer it.\n\n```\n{{code}}\n```'],
    ['coding', 'Make it faster', 'Profile this code in your head: where is the time going? Suggest the 3 changes with the biggest speed-up, with code.\n\n```\n{{code}}\n```'],
    ['coding', 'Regex builder', 'Write a {{flavor|JavaScript,Python,PCRE}} regular expression that matches {{what}}. Give 3 strings it matches and 3 it must not, and explain each part briefly.'],
    ['coding', 'Convert code', 'Convert this code from {{from=JavaScript}} to {{to=Python}}, idiomatically (not line by line). Note anything that has no direct equivalent.\n\n```\n{{code}}\n```'],
    ['coding', 'Explain an error message', 'I got this error:\n\n```\n{{error}}\n```\n\nWhat does it mean, what most likely caused it, and how do I fix it? Context: {{context=plain JS in an Electron app}}'],
    ['coding', 'Write a function', 'Write a {{language=JavaScript}} function that {{task}}. Small, no dependencies, with a one-line comment and an example call.'],
    ['coding', 'Code golf to clarity', 'This snippet is too clever. Rewrite it so a beginner can follow it, with short comments.\n\n```\n{{code}}\n```'],
    ['coding', 'Electron IPC handler', 'In my Electron app (plain JS, contextBridge preload exposing window.hub), add an IPC call that {{task}}. Show the main.js handler, the preload line and a renderer usage example. Keep it safe: validate paths and inputs.'],
    ['coding', 'Debounce / throttle this', 'This handler fires too often: {{situation}}. Show how to debounce or throttle it (pick the right one and say why).\n\n```js\n{{code}}\n```'],
    ['coding', 'Name things better', 'Suggest clearer names for the variables and functions in this code. Give a table: old name, new name, why.\n\n```\n{{code}}\n```'],
    ['coding', 'Find edge cases', 'List the edge cases this code doesn\'t handle (empty input, huge input, unicode, timing, nulls…), most likely to bite first.\n\n```\n{{code}}\n```'],
    ['coding', 'Write a CLI script', 'Write a small Node.js script (no npm packages) that {{task}}. Read args from process.argv, print progress, exit non-zero on failure.'],
    ['coding', 'JSON shape → code', 'Here is some JSON. Write a {{language=JavaScript}} function that validates it and pulls out {{fields}}.\n\n```json\n{{json}}\n```'],
    ['coding', 'Git help', 'In git, how do I {{task}}? Give the exact commands, what each does, and how to undo it if I get it wrong.'],
    ['coding', 'CSS layout fix', 'My layout is wrong: {{problem}}. Here is the HTML/CSS. Fix it with modern CSS (flex/grid), minimal changes.\n\n```\n{{code}}\n```'],
    ['coding', 'Commit message', 'Write a clear git commit message (subject ≤ 60 chars, then a short body) for this change:\n\n{{diff}}'],
    ['coding', 'Memory leak hunt', 'This page gets slower over time. Look for leaks: listeners never removed, growing arrays/maps, timers, detached DOM, GPU resources not disposed.\n\n```js\n{{code}}\n```'],

    // ---------- three.js & shaders ----------
    ['three', 'Three.js performance review', 'Review this three.js code for performance (draw calls, allocations in the render loop, overdraw, texture sizes) and suggest concrete fixes:\n\n```js\n{{code}}\n```'],
    ['three', 'New visualizer sketch', 'Make a new three.js music visualizer: {{idea}}. Mood: {{mood|dreamy,aggressive,minimal,neon,organic,cosmic}}. Frame: {{frame|9:16 Shorts,16:9,1:1,4:5}}. Add clearly named tweak() sliders (colors, motion, intensity) and react to the kick and the highs.'],
    ['three', 'Write a fragment shader', 'Write a GLSL fragment shader that {{effect}}. Uniforms: uTime, uResolution{{extra_uniforms=, uAudio (0–1 bass level)}}. Comment the key lines. Make it look good by default.'],
    ['three', 'Explain this shader', 'Explain this shader line by line in plain words, then tell me which 3 numbers to change for the biggest visual difference:\n\n```glsl\n{{shader}}\n```'],
    ['three', 'ShaderMaterial from GLSL', 'Wrap this fragment shader in a three.js ShaderMaterial on a fullscreen quad, with uniforms updated every frame (time, resolution, audio level):\n\n```glsl\n{{shader}}\n```'],
    ['three', 'Post-processing stack', 'Add a post-processing stack to my scene: {{effects=bloom, chromatic aberration, film grain, vignette}}. Use EffectComposer, keep it cheap, and expose each strength as a tweak() slider.'],
    ['three', 'Particle system', 'Build a GPU-friendly particle system in three.js: {{count=50000}} particles that {{behavior}}. Use BufferGeometry + Points (or instancing), update in a shader if possible, and make particle size and color react to the music.'],
    ['three', 'Instanced mesh field', 'Make a field of {{count=2000}} instanced {{shape|cubes,spheres,shards,rings,blades of grass}} that ripple to the beat. Use InstancedMesh, one draw call, per-instance color.'],
    ['three', 'Camera choreography', 'Give my scene a camera move that {{move|slowly orbits,pushes in on the drop,shakes on the kick,drifts like a handheld,cuts between 4 angles every 2 bars}}. Smooth (damped), with sliders for speed and amount.'],
    ['three', 'Raymarching scene', 'Write a raymarched SDF scene in a fragment shader: {{scene}}. Soft shadows, ambient occlusion, fog, and a uniform for audio-driven deformation. Keep it under ~120 lines.'],
    ['three', 'Noise flow field', 'Create a curl-noise flow field with trails in three.js (ping-pong render targets or line trails). Colors from the palette global, speed from the music.'],
    ['three', 'Material look-dev', 'Give this object a {{look|chrome,glass,iridescent,holographic,clay,neon wireframe,brushed metal,velvet}} material in three.js. Include environment lighting, tone mapping and the exact MeshPhysicalMaterial settings.'],
    ['three', 'Fix black screen', 'My three.js sketch shows a black screen. Check the usual causes (camera inside/behind objects, no light with lit materials, near/far planes, renderer size 0, color space, NaN in positions) against this code:\n\n```js\n{{code}}\n```'],
    ['three', 'GLSL noise toolbox', 'Give me a compact GLSL toolbox: hash, value noise, simplex 2D/3D, fbm and domain warping, each with a one-line usage note.'],
    ['three', 'Port Shadertoy', 'Port this Shadertoy shader to a three.js ShaderMaterial (map iTime, iResolution, iMouse, iChannel0 to uniforms):\n\n```glsl\n{{shader}}\n```'],
    ['three', 'Text in 3D', 'Show the text "{{text}}" in my three.js scene as {{style|extruded 3D letters,glowing outline,particles forming the letters,SDF text on a plane}}, animated in on the beat.'],
    ['three', 'Optimize for 60 fps', 'This sketch drops below 60 fps at 1080×1920. Find the expensive parts and propose a cheaper version that looks almost the same.\n\n```js\n{{code}}\n```'],
    ['three', 'Color grading in shader', 'Write a final color-grade pass (GLSL): lift/gamma/gain, saturation, a {{grade|teal & orange,bleach bypass,cross-process,warm film,cold night,monochrome tint}} look, and a LUT-free contrast curve, all as uniforms.'],
    ['three', 'Feedback / trails effect', 'Add a video-feedback trails effect: render the previous frame slightly zoomed, rotated and faded under the new one. Sliders for decay, zoom and hue drift.'],
    ['three', 'Audio-reactive mapping ideas', 'For a {{genre=melodic techno}} track, suggest 8 ways to map audio features (kick, snare, bass level, highs, beat in bar, bar count) to visual parameters in my sketch. Be specific about ranges and easing.'],
    ['three', 'Scene from a reference picture', 'Recreate the feeling of my reference picture ({{describe}}) as a three.js scene: composition, palette, lighting and motion. Start simple, then add detail.'],
    ['three', 'Load and style a GLTF', 'Load a GLTF model, center and scale it to fit, give it a {{look=chrome}} material override, add rim light, and make it pulse with the kick.'],

    // ---------- music visuals ----------
    ['music', 'Visual concept for a track', 'Give me 5 visual concepts for a music visualizer for "{{track}}" ({{genre}}). For each: one-line idea, palette (hex), motion, what reacts to what, and the moment it peaks.'],
    ['music', 'Drop moment ideas', 'The drop is at {{time=1:04}}. Give me 6 ideas for what the visual does in the 2 bars before and on the drop (build-up, silence, impact), from subtle to huge.'],
    ['music', 'Beat-sync plan', 'Here is the song structure: {{structure=intro 8 bars, build 8, drop 16, break 8, drop 16, outro 8}}. Plan the visual per section: what changes, what stays, and what hits on kick / snare / bar.'],
    ['music', 'Palette for a mood', 'Suggest 4 color palettes (5 hex colors each) for a visual that feels {{mood}}. Name each palette and say which color goes to background, main shape, accent and highlights.'],
    ['music', 'Loop-friendly idea', 'Design a visual that loops perfectly every {{bars=4}} bars at {{bpm=124}} BPM: tell me the loop length in seconds and frames ({{fps=60}} fps) and how to make every motion periodic.'],
    ['music', 'Lyric video style', 'Plan a lyric video style for these lines: {{lyrics}}. Typography, motion per word, how it reacts to the beat, and transitions between lines.'],
    ['music', 'Album cover → visual', 'Here is the album cover description / palette: {{cover}}. Turn it into a matching visualizer: shapes, textures, motion and the colors in hex.'],
    ['music', 'Genre visual language', 'What visual language fits {{genre}}? Give me references (styles, not specific artists\' works), typical shapes, motion speed, color temperature and editing rhythm.'],
    ['music', 'Spectrum design alternatives', 'Give me 8 alternatives to a classic bar spectrum for showing frequencies (radial, terrain, particles, rings…), each with a one-line three.js approach.'],
    ['music', 'Build-up tension tricks', 'List 10 visual tricks to build tension during a riser: shake, speed, zoom, strobe, color shift, chromatic aberration… with how each maps to the riser progress 0→1.'],
    ['music', 'Shorts hook (first 2 s)', 'My visual for "{{track}}" goes on {{platform|YouTube Shorts,TikTok,Instagram Reels}}. What should happen in the first 2 seconds to stop the scroll? Give 5 concrete openings.'],
    ['music', 'Visualizer series plan', 'Plan a series of {{count=6}} visualizers with a consistent look for my channel: shared elements, what varies per track, naming and thumbnail style.'],
    ['music', 'Map drums to motion', 'Kick at {{bpm=128}} BPM, snare on 2 and 4, hats on 8ths. Write the JS that turns audio.kick / audio.snare into smooth envelopes (attack/decay in ms) to drive scale, flash and camera shake.'],
    ['music', 'Ambient / no-beat visual', 'This track has no clear beat ({{genre=ambient}}). Suggest how to drive the visual from slow features instead: loudness, brightness, stereo width, section changes.'],
    ['music', 'Transitions between scenes', 'My visual has {{count=3}} scenes. Give me 6 transition ideas between them that land on a bar line (wipes, morphs, glitch cuts, zoom-throughs), with how to time them.'],
    ['music', 'Live set visual cues', 'I\'m doing visuals for a live set. Make a cue sheet template: track, BPM, key moments, which preset/look, and fallback if the audio analysis fails.'],
    ['music', 'Title card for a track', 'Design a title card for "{{track}}" by {{artist}} that appears for the first {{seconds=3}} seconds: font style, motion in/out, placement safe for {{frame|9:16,16:9,1:1}}.'],
    ['music', 'Describe this sound visually', 'Describe this sound in visual terms (shape, texture, color, motion): {{sound}}. Then give 3 ways to render it in three.js.'],

    // ---------- after effects ----------
    ['ae', 'After Effects expression', 'Write an After Effects expression for the {{property}} property that {{behavior}}. Return only the expression and a one-line note on where to paste it.'],
    ['ae', 'ExtendScript for After Effects', 'Write an After Effects ExtendScript (.jsx) that {{task}}. It runs inside an undo group already. Use app.project.activeItem for the current comp and alert() for errors.'],
    ['ae', 'Audio-driven expression', 'Write an AE expression that drives {{property=Scale}} from the "Audio Amplitude" layer\'s {{channel|Both Channels,Left Channel,Right Channel}} slider, with a threshold, smoothing and a max value I can tweak at the top.'],
    ['ae', 'Wiggle with control', 'Write a wiggle expression for {{property=Position}} driven by Slider Controls (frequency, amount) on a "Controls" null, that can fade in/out with a third slider.'],
    ['ae', 'Loop keyframes', 'Give me the expression to loop keyframes on {{property}} as {{mode|cycle,pingpong,offset,continue}}, and explain the difference between loopOut and loopIn here.'],
    ['ae', 'Bounce / overshoot', 'Write an inertial bounce (overshoot) expression for {{property=Scale}} after each keyframe, with amplitude, frequency and decay at the top.'],
    ['ae', 'Text animator recipe', 'Give me step-by-step settings for a text animator in AE that {{effect=types each word in with a blur and slight upward move}}: animator properties, range selector settings, easing.'],
    ['ae', 'Render settings for platform', 'What render / output settings should I use in AE + Media Encoder for {{platform|YouTube 4K,YouTube Shorts,Instagram Reels,TikTok,itch.io trailer}}? Codec, bitrate, frame rate, color, audio.'],
    ['ae', 'Batch rename layers script', 'Write an ExtendScript that renames the selected layers using the pattern "{{pattern=Shape ##}}" (## = index) and keeps their order.'],
    ['ae', 'Beat markers script', 'Write an ExtendScript that adds layer markers every beat on the selected layer for {{bpm=120}} BPM starting at {{offset=0}} seconds, labelling every bar.'],
    ['ae', 'Shape layer recipe', 'How do I build {{shape}} with shape layers only (no plugins)? Give the group structure, operators (repeater, trim paths, offset…) and key values.'],
    ['ae', 'Fix slow comp', 'My AE comp previews slowly: {{details}}. List what to check and change, from biggest win to smallest (pre-comps, motion blur, effects order, resolution, caching).'],
    ['ae', 'Camera shake expression', 'Write a camera-shake expression for a 3D camera\'s point of interest and position, with intensity driven by a slider and an optional link to audio amplitude.'],
    ['ae', 'Kinetic typography plan', 'Plan a kinetic typography piece for this text: {{text}}. Timing per phrase at {{bpm=100}} BPM, transitions, emphasis words and fonts.'],
    ['ae', 'Color match two shots', 'Shot A looks {{a}}, shot B looks {{b}}. Which AE effects and settings (Lumetri, Curves, Levels) bring B close to A?'],

    // ---------- game dev & forgeheart ----------
    ['game', 'itch.io devlog post', 'Write an itch.io devlog post for Forgeheart about: {{topic}}. Friendly, concise, with a short intro, bullet list of changes and a call to action.'],
    ['game', 'Patch notes polish', 'Turn these raw notes into player-facing patch notes grouped under New, Changes, Balance and Fixes:\n\n{{notes}}'],
    ['game', 'Design a new enemy', 'Design a new Forgeheart enemy: role {{role|swarm,tank,ranged,elite,support,boss add}}. Name, look, movement, attack pattern, counterplay, stats relative to existing foes, and the stage it should first appear.'],
    ['game', 'Design a unique item', 'Design a unique (★) item for slot {{slot|weapon,helmet,chest,gloves,boots,ring,amulet,drone core}}: name, base, 3–4 affixes with numbers, one build-defining effect, and what build it enables.'],
    ['game', 'Balance pass on numbers', 'Here are current numbers: {{numbers}}. The problem: {{problem}}. Propose a balance change with exact new values and what to watch in playtests.'],
    ['game', 'Boss fight design', 'Design a boss for stage {{stage=50}}: phases, attacks with telegraphs, arena, what it tests in the player\'s build, and the loot.'],
    ['game', 'Progression curve check', 'Check this progression curve for walls and dead zones (gold, damage, enemy HP per stage): {{data}}. Suggest a smoother formula.'],
    ['game', 'Game feel juice list', 'List 12 cheap "juice" upgrades for {{action=hitting an enemy}} in a browser survivor game: screenshake, hitstop, particles, sound layering, number popups… with how strong each should be.'],
    ['game', 'Playtest questions', 'Write 10 playtest questions for testers of {{feature}} that reveal confusion and fun without leading them.'],
    ['game', 'Bug report → fix plan', 'Bug report from a player: "{{report}}". What are the likely causes in a single-file HTML game, how do I reproduce it, and what would the fix look like?'],
    ['game', 'Tutorial text', 'Write short, friendly tutorial tooltips (max 12 words each) for: {{steps}}.'],
    ['game', 'Achievement ideas', 'Give me 20 achievement ideas for Forgeheart (forging, drones, rifts, factory, bosses): name, condition, and a fun description. Mix easy, grindy and secret.'],
    ['game', 'Factory system idea', 'Suggest a new factory/automation building for Forgeheart that {{goal}}: inputs, outputs, upgrade levels, and how it interacts with drones and forging.'],
    ['game', 'Affix brainstorm', 'Brainstorm 15 new affixes (prefixes and suffixes) for {{slot=weapons}} that create interesting choices, with value ranges per tier.'],
    ['game', 'Store page copy', 'Write the itch.io store page for Forgeheart: hook line, short description (3 sentences), feature bullets, and 5 tags.'],
    ['game', 'Save-data migration', 'My save format changes: {{change}}. Write a JS migration that upgrades old saves safely (versioned, never loses items), with a test save example.'],
    ['game', 'Performance in the game loop', 'Here is my game loop / hot function. Find allocations and slow paths per frame, and rewrite it for {{count=500}} enemies at 60 fps.\n\n```js\n{{code}}\n```'],
    ['game', 'Debug-patch request', 'In the live debug game: {{change}}. Keep it as a saved patch named "{{name}}" so it survives reloads, then check it with a status and a screenshot.'],

    // ---------- writing ----------
    ['writing', 'Rewrite clearer', 'Rewrite this so it\'s clearer and shorter, same meaning, {{tone|friendly,neutral,formal,punchy}} tone:\n\n{{text}}'],
    ['writing', 'Fix grammar only', 'Fix spelling and grammar only. Don\'t change my style or wording otherwise. Show the corrected text, then the changes as a short list.\n\n{{text}}'],
    ['writing', 'Translate', 'Translate to natural {{language|French,English,Spanish,German,Italian,Japanese}} (not word for word), keep the tone:\n\n{{text}}'],
    ['writing', 'Translate to French', 'Translate to natural French:\n\n{{text}}'],
    ['writing', 'Summarize', 'Summarize this in {{length=5}} bullet points:\n\n{{text}}'],
    ['writing', 'TL;DR + key points', 'Give me a one-sentence TL;DR, then the key points, then anything I need to act on:\n\n{{text}}'],
    ['writing', 'Write an email', 'Write an email to {{to}} about {{subject}}. Goal: {{goal}}. {{tone|Friendly,Polite and formal,Short and direct}}. Under 150 words.'],
    ['writing', 'Reply to this message', 'Help me reply to this message. I want to {{intent}}. Keep it {{tone|warm,neutral,firm,brief}}.\n\n{{message}}'],
    ['writing', 'Brainstorm names', 'Give me 15 name ideas for {{thing}}. Mix styles: short, descriptive, playful. Mark your top 3.'],
    ['writing', 'Make it more vivid', 'Make this description more vivid and concrete (sensory details, strong verbs) without making it longer than {{words=120}} words:\n\n{{text}}'],
    ['writing', 'Outline an article', 'Outline an article about {{topic}} for {{audience}}: title options, sections with one-line summaries, and a strong opening line.'],
    ['writing', 'Bio in three lengths', 'Write my bio as a {{role=music visual artist and indie game dev}} in 3 lengths: one line, 50 words, 150 words. Facts: {{facts}}.'],
    ['writing', 'Explain like I\'m 12', 'Explain {{topic}} like I\'m 12, with one everyday analogy and no jargon.'],
    ['writing', 'Tone check', 'How does this message come across (tone, possible misreadings)? Suggest a version that sounds {{target|kinder,more confident,more professional,more casual}}.\n\n{{text}}'],
    ['writing', 'Headline variations', 'Give me 10 headline variations for: {{topic}}. Mix curiosity, benefit and plain-descriptive styles.'],

    // ---------- social ----------
    ['social', 'Caption for a visual', 'Write {{count=5}} captions for my music visual "{{title}}" ({{vibe|hypnotic,dark,euphoric,chill,glitchy,cosmic}}). Short, no cringe, max 1 emoji each, and a hashtag set (8 tags) at the end.'],
    ['social', 'YouTube Shorts title + description', 'For my YouTube Short of a visualizer for "{{track}}" by {{artist}}: give 5 titles (under 60 characters), a 2-line description with credit, and 10 hashtags.'],
    ['social', 'TikTok caption + hook text', 'For a TikTok of my visual "{{title}}": an on-screen hook (max 7 words), a caption, and 5 hashtags that real people search.'],
    ['social', 'Instagram carousel text', 'Write slide texts for an Instagram carousel of {{count=5}} frames from my visual "{{title}}": one short line per slide, then the caption.'],
    ['social', 'Hashtag set', 'Give me 3 hashtag sets (mixed sizes: big, mid, niche) for posts about {{topic=three.js music visualizers}}. 10 tags each.'],
    ['social', 'Credit the artist', 'Write a short, respectful credit line for using "{{track}}" by {{artist}} in my visual, plus a polite DM asking if I can tag them.'],
    ['social', 'Behind the scenes post', 'Write a behind-the-scenes post about how I made "{{title}}" with code (three.js) and music: 4 short paragraphs, accessible, ends with a question to the audience.'],
    ['social', 'Thread about a technique', 'Write an X/Bluesky thread (6 posts) explaining {{technique}} with a visual example in mind. First post is the hook.'],
    ['social', 'Reply to a comment', 'Reply to this comment on my post, {{tone|grateful,funny,helpful,short}}: "{{comment}}"'],
    ['social', 'Weekly content plan', 'Plan a week of posts for my visuals account ({{platforms=TikTok, Shorts, Instagram}}): what to post each day, format, hook, and best time.'],
    ['social', 'Repurpose one visual', 'I have one finished visual "{{title}}". Give me 8 ways to repurpose it into different posts (crops, loops, breakdowns, before/after, stills…).'],
    ['social', 'Profile bio', 'Write 5 profile bios (max 150 chars) for my account that makes {{what=code-driven music visuals}}. Include one call to action.'],
    ['social', 'Collab pitch to an artist', 'Write a short pitch to {{artist}} offering a visualizer for their track "{{track}}". Mention my style ({{style}}), keep it under 100 words, no pressure.'],
    ['social', 'Thumbnail text ideas', 'Give me 10 thumbnail text ideas (max 4 words) for a video about {{topic}}, plus which frame of the visual to use for each.'],
    ['social', 'itch.io / devlog social blurb', 'Turn this devlog into a 2-sentence social post with a link placeholder and 4 hashtags:\n\n{{devlog}}'],
    ['social', 'Post-performance review', 'My post "{{title}}" got {{stats}}. What probably worked or didn\'t (hook, length, caption, timing), and what should I try next time?'],
    ['social', 'Alt text for a frame', 'Write alt text (under 200 characters) for a frame of my visual that shows: {{describe}}.'],
    ['social', 'Caption in two languages', 'Write a caption for "{{title}}" in English and French, same vibe, max 2 lines each, plus 6 hashtags.'],

    // ---------- review & critique ----------
    ['review', 'Critique my visual', 'Critique my visual honestly like an art director: composition, color, motion, rhythm with the music, readability on a phone. What are the 3 changes that would improve it most? Description / screenshot: {{describe}}'],
    ['review', 'Code review', 'Review this code like a senior engineer: bugs first, then risky patterns, then style. Be concise; show fixes as small diffs.\n\n```\n{{code}}\n```'],
    ['review', 'Second opinion on a plan', 'Here is my plan: {{plan}}. Poke holes in it: what could go wrong, what I\'m missing, and a cheaper alternative.'],
    ['review', 'Review my writing', 'Review this text: what\'s unclear, what\'s too long, what\'s strong. Then a revised version.\n\n{{text}}'],
    ['review', 'UI / UX review', 'Review this UI: {{describe}}. Look at hierarchy, clutter, labels, discoverability and accessibility. List fixes by impact.'],
    ['review', 'Compare two options', 'Compare {{a}} and {{b}} for {{goal}}: a table of pros/cons, then a clear recommendation and when I\'d pick the other one.'],
    ['review', 'Red team this idea', 'Argue against this idea as convincingly as you can, then tell me which objections actually matter: {{idea}}'],
    ['review', 'Check my math', 'Check this calculation / formula step by step and point out any error: {{math}}'],
    ['review', 'Thumbnail critique', 'Critique this thumbnail idea for click-through on a phone: {{describe}}. Contrast, text size, focal point, curiosity.'],
    ['review', 'Game design review', 'Review this game mechanic as a designer: {{mechanic}}. Is it fun, readable, exploitable? Suggest one tweak that makes it more interesting.'],
    ['review', 'Accessibility check', 'Check this for accessibility issues (contrast, keyboard use, motion sensitivity, flashing — important for strobe visuals) and suggest fixes: {{describe}}'],
    ['review', 'Rate it 1–10 with reasons', 'Rate this from 1 to 10 for {{criteria=originality, polish and clarity}}, with one sentence per criterion and one thing that would raise the score: {{thing}}'],

    // ---------- planning ----------
    ['plan', 'Break into tasks', 'Break this project into small tasks (each under 2 hours), in order, with the first one I can start right now: {{project}}'],
    ['plan', 'Plan my day', 'Help me plan today. Must do: {{must}}. Would like to: {{nice}}. I have {{hours=6}} hours. Give a realistic schedule with breaks.'],
    ['plan', 'Weekly review', 'Run a quick weekly review with me: what I shipped ({{shipped}}), what slipped ({{slipped}}). Suggest 3 priorities for next week and one thing to stop doing.'],
    ['plan', 'Release checklist', 'Make a release checklist for {{what=a Forgeheart update on itch.io}}: build, test, notes, upload, announce, after-release checks.'],
    ['plan', 'Decide between options', 'Help me decide: {{options}}. Ask me up to 3 questions first if you need to, then recommend one with reasons.'],
    ['plan', 'Project kickoff', 'Kick off a new project: {{project}}. Goal, scope (in/out), first milestone, risks, and the smallest version I could finish this week.'],
    ['plan', 'Estimate effort', 'Estimate how long {{task}} would take a solo developer, with best/likely/worst cases and the biggest unknowns.'],
    ['plan', 'Roadmap for a month', 'Draft a one-month roadmap for {{project}}: weekly goals, one visible result per week, and buffer time.'],
    ['plan', 'Learning plan', 'Make a {{weeks=4}}-week learning plan for {{skill}} for someone who learns by making things. One small project per week.'],
    ['plan', 'Meeting / call prep', 'Prepare me for a call about {{topic}} with {{who}}: goals, questions to ask, things to avoid, and a 2-line summary of my position.'],
    ['plan', 'Unblock me', 'I\'m stuck on {{problem}}. I\'ve tried: {{tried}}. Give me 3 different angles to attack it and the quickest experiment for each.'],
    ['plan', 'Turn notes into actions', 'Turn these notes into a list of concrete next actions (verb first), grouped by project, with anything waiting on someone else marked:\n\n{{notes}}'],

    // ---------- learning ----------
    ['learn', 'Teach me a concept', 'Teach me {{concept}} in 5 short steps, each with a tiny example I can try in a three.js sketch or the browser console.'],
    ['learn', 'Quiz me', 'Quiz me on {{topic}} with 5 questions, one at a time. Wait for my answer before the next one, and explain my mistakes.'],
    ['learn', 'Explain the math', 'Explain the math behind {{thing=quaternions in three.js}} visually and intuitively first, then the formula, then code.'],
    ['learn', 'Cheat sheet', 'Make a one-page cheat sheet for {{topic}}: the 20% that covers 80% of daily use, with code snippets.'],
    ['learn', 'Compare concepts', 'What is the difference between {{a}} and {{b}}? When do I use each? One example of each.'],
    ['learn', 'Reverse-engineer an effect', 'How would you recreate this effect I saw: {{describe}}? Break it into layers/techniques and give a starting point in code.'],
    ['learn', 'Glossary', 'Make a glossary of the 15 terms I need for {{field=real-time graphics}}, one plain sentence each.'],
    ['learn', 'Exercises', 'Give me 5 progressively harder exercises to practise {{skill}}, each with a hint and what "done" looks like.'],

    // ---------- everyday ----------
    ['basics', 'Continue', 'Continue from where you stopped.'],
    ['basics', 'Shorter answer', 'Give me that again in {{lines=3}} lines max.'],
    ['basics', 'Step by step', 'Walk me through that step by step, one step at a time, waiting for me to say "next".'],
    ['basics', 'Give me options', 'Give me {{count=3}} different options for this, with a one-line trade-off each: {{thing}}'],
    ['basics', 'Pros and cons', 'Pros and cons of {{thing}}, as a short table, then your verdict.'],
    ['basics', 'Make a table', 'Turn this into a clean Markdown table with sensible columns:\n\n{{text}}'],
    ['basics', 'Extract to JSON', 'Extract {{fields}} from this text as a JSON array. Only JSON, no comments:\n\n{{text}}'],
    ['basics', 'What am I missing?', 'Given everything above, what am I missing or not asking that I should?'],
    ['basics', 'Check before you answer', 'Before answering, list your assumptions about {{topic}} and ask me about the ones that matter. Then answer.'],
    ['basics', 'Recap this chat', 'Recap this conversation: decisions made, open questions, and next steps.'],
  ];
  const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
  return { CATS, list: P.map(([cat, name, text]) => ({ id: `b:${slug(name)}`, cat, name, text, builtin: true })) };
})();
