// Forge Debug checks against dev/fake-forgeheart.html (pass its absolute path in window.__fakeGame via --eval first):
//   node dev/smoke.js --eval "window.__fakeGame='/abs/path/dev/fake-forgeheart.html'" --script dev/forge-checks.js --shot /tmp/forge.png
const out = {};
const agentId = H.claudeAgent().id;
const ctx = { agentId, chatId: null, input: null, say: () => {}, draft: () => {}, send: () => {} };
const run = async (line) => { const hit = Commands.parse(line); try { const r = await hit.def.run(hit.args, ctx); return typeof r === 'string' ? r.replace(/\s+/g, ' ').slice(0, 220) : '(no text)'; } catch (e) { return `ERROR ${e.message}`; } };
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
H.config.settings = { ...H.config.settings, forgeDebugBuild: window.__fakeGame };
H.config.agents.push({ id: 'forge-debug', name: 'Forge Debug', icon: '⚒', color: '#e07a2f', mode: 'native', engine: 'claude', gameTools: true, companion: 'forge-game', askAll: false });
await saveConfig();
await sleep(1500);
out.status = await run('/forge-status');
out.spawn = await run('/forge-spawn drone 12');
out.boss = await run('/forge-boss');
out.god = await run('/forge-god on');
out.gold = await run('/forge-gold 5k');
out.stage = await run('/forge-stage 7');
out.next = await run('/forge-next');
out.eval = await run('/forge-eval S.stage * 2');
out.watch = await run('/forge-watch C.en.length');
out.snap = await run('/forge-snap Stage 8 test');
await run('/forge-stage 30');
out.restore = await run('/forge-restore Stage 8');
await sleep(800);
out.afterRestore = await run('/forge-eval S.stage');
await ForgeGame.handleTool('forge_patch_save', { name: 'rich', code: 'S.gold = 999999; true', description: 'test' });
out.setSave = await run('/forge-set save money');
out.patchOff = await run('/forge-patch rich off');
out.setList = await run('/forge-set');
out.setUse = await run('/forge-set use money');
await sleep(800);
out.goldAfterSet = await run('/forge-eval S.gold');
out.kill = await run('/forge-kill');
out.speed = await run('/forge-speed 2');
await run('/forge-spawn wisp 5');
await sleep(1300);
out.watchRows = [...document.querySelectorAll('.fg-watch-row')].map((r) => r.textContent).join(' | ');
activate('forge-debug');
await run('/forge-spawn drone 30');
await sleep(1500);
return JSON.stringify(out, null, 1);
