// The app map: what Hearth is and how its pieces fit, for both engines (Claude and Astra) when they direct a tool.
// Read on demand only (three_do { cmd: "help", topic } in the Lab, hearth_help { topic } elsewhere); the system
// prompt carries one short line pointing here (LINE, ≈ 60 tokens), so nothing grows on every message.
// Keep each topic short and factual: it is what a fresh engine reads before picking up the owner's work.

const TOPICS = {
  app: `HEARTH is the owner's desktop app: one window for their AI agents. Native chats run Claude (Claude Code) and Astra (Codex / ChatGPT) on the owner's own subscriptions. Directors are chats docked next to a tool: the Three Director beside the Three.js Lab, the Video Director beside Video Review, Forge Debug beside their game.
  Each director chat owns its own Lab scene: your tool calls reach your chat's scene (on screen, or backstage while the owner looks at another chat).
  Claude and Astra are interchangeable directors: same tools, same guide, same chat, same scene. Hearth keeps the chat's task state for whoever runs next (topic handoff).
  Everything is drivable by chat commands (/name args); suggest them to the owner, run Lab ones yourself (topic commands).
  The owner doesn't write code; they describe, then shape results with sliders, looks, frame sizes and the timeline. They want few choices: decide small things yourself.
  Topics: lab, nodes, react, commands, handoff, habits, video, editor, sequence, motion, comp, board, capture, intro, then the Lab's own (layers, sliders, keyframes, timeline, filters, looks, audio, refs, notes, scene, live, games, frame, bigcode).`,
  lab: `THE LAB'S MODEL (After Effects with code), bottom up:
  sketch (one per director chat; the owner's other sketches stay untouched)
  → layers, stacked bottom first; each is its own three.js module (renderer, scene, camera), with opacity, blend, x / y / scale / rotate and an in / out time on the song with fades. Filter layers (ascii, vhs, glitch, crt, glow…) restyle every layer below them.
  → per layer: tweak() sliders (the owner's knobs: Save, Shuffle, undo, ♪ links to the music), keyframes on slider values and layer settings, looks (saved slider sets, morphed by cues).
  → node graphs: the Nodes view (Alt+N) shows a layer as nodes + wires; the graph compiles to the layer's code and its knobs are the layer's sliders (topic nodes).
  → the timeline: one clock per scene. The song (beat grid, kick / snare / hit markers), else the scene's OWN timeline (no song: a length, 10 s by default, frame-exact at 30 fps; keyframes, cues, the loop and timeline edits all work on it, nothing reacts to music). Named cues (Intro, Drop…), layer tracks with keyframe lanes. three_do timeline_edit { length: 20 } sets the own timeline's length; a song loaded later keeps every keyframe and cue at its seconds (timeline_edit { snapToBars: true } puts them on its bars). The scene's sequence starts with the scene as its clip.
  → a NEW chat's scene is the orb: two node layers (Backdrop, Orb: Timeline → Glowing orb + Orb halo + Camera) in the chat's color, keyframes already on the Orb layer's sliders (size, glow, camera distance / height). Change it with three_nodes and keyframes; make it react only when asked.
  → video footage instead of (or with) a song: exact frames (media.frame, media.onFrame), a timecode counter, a cut list the sketch plays, shared with the editor (topic footage).
  → the Lab sequence: several scenes, footage and titles on one video timeline, played in the preview and rendered frame by frame (topic sequence).
  The owner's habits: Save and Shuffle sliders constantly, switch social frame sizes (9:16, 1:1, 4:5, 16:9), Freeze frames, Present, record to Video Review.`,
  nodes: `NODES (three_nodes { command }): build visual layers as node graphs so the owner sees what you made in the Nodes view.
  "layer <preset>" adds a NEW layer from a preset (presets [word] lists them: ⏱ = timeline-driven, ♪ = reacts to music) · "preset <preset>" replaces the selected layer · "add <type> k=v… to=node.input" · "link a.out b.in" · "unlink b.in" · "set <node> k=v…" · "rm <node…>" · "list" (the graph, changed values, wires) · "types [word]" (types with their ports) · "layout" · "rebuild".
  Categories: Objects (mesh, particles, tunnel, gridCopies, ringCopies, blob, wavePlane, imagePlane, spectrumBars…), Shapes, Materials, Lights, Motion (spin, move, orbit, bounce, wobble, pulse…), Camera, Time (timeline = the scene's own clock, keys = keyframes on it, time, lfo, noiseWave, ramp), orb / orbHalo / backdrop (the new-chat orb), Layer (layerTime), Music + Triggers (only when asked to react), Math, Colors (palette, mixColors, rainbow…), Post (bloom, trails, rgbShift, film, kaleido…), Output.
  Change a node layer with three_nodes: a code edit makes its graph read-only. What nodes can't express goes in a code layer of its own (three_add_layer).`,
  react: `MUSIC REACTIVITY (only when the owner asks: "make it react", "hit on the kick", "sync it to the beat"):
  Fast way: three_do { cmd: "run", command: "/make-it-react" } links sensible sliders to the kick, bass and loudness by their names ("/make-it-react undo" takes it back).
  Nodes: wire Music nodes into what should move (hits.kick → peak → pulse.amount, levels.bass → smooth → remap → mesh.scale).
  Code: the audio globals (help audio); build hits on the owner's markers (audio.kick / snare / hit) when the song has them.
  Until then, scenes move on the timeline: time, keyframes, easing, cues and sections (help keyframes, help timeline).`,
  commands: `CHAT COMMANDS: the owner types /name args. Offer them as <suggest>/name …</suggest>; run Lab, music, nodes and video ones yourself with three_do { cmd: "run", command: "/name args" } (results come back as text).
  Lab: /save-look, /shuffle [colors], /fix-errors, /size 9:16, /freeze, /present, /record, /layer.
  Music: /make-it-react [undo], /analyze, /drops next, /downbeat, /auto-preset.
  Footage: /footage [go f120|step n|cut|delete|scenes|editor], /match-pacing <clip>, /ref-frames <clip>.
  Nodes: /nodes, /nodes-layer <preset>, /nodes-presets.
  Director: /undo-edit, /redo-edit, /director-engine claude|astra, /handoff, /task, /director-cost, /director-mode lean|full, /nodes-director on|off.
  Together: /jam (Claude ⇄ Astra build a visual in turns), /opinion (second opinion).
  Video: /help video. Everything else: /help <area>.`,
  handoff: `HANDOFF: Hearth (not the model) keeps each director chat's task state: the goal, recent asks, what was done (layers added, edits, nodes, keyframes…), the scene's layers, open todos and the last screenshot. Whichever engine runs next in the chat gets it once as "[Task state…]" (after /director-engine, /handoff or the ⚇ menu's switch), so Claude can pick up Astra's work and the other way round, in the same chat and scene. Read it any time: three_do { cmd: "task" }. Keep todos current with chat_progress (or three_do { cmd: "task", todo: [...] }) so the next one knows what's left.`,
  habits: `HABITS the owner asked for:
  1. Every new effect or element = a NEW layer (three_add_layer, three_nodes "layer …"), never piled into one big layer. Rewrite an existing layer (three_set_code / update_layer code) only when the owner asks to; small changes: three_edit_code.
  2. Visual layers as node graphs (three_nodes) so the Nodes view always shows what you made.
  3. Time first, like After Effects: motion from time, keyframes, easing, cues and sections; music reactivity only when asked (topic react).
  4. Knobs, not code: tweak() sliders with plain labels and groups; keep the owner's unsaved slider values.
  5. Look before claiming it works (three_screenshot small, or shot: true on an edit); fix errors first.
  6. Decide small things yourself; ask (chat_ask) only for real choices. Don't paste code: say what you made and what to ask next.`,
  capture: `CAPTURE (Hearth screenshots / records itself; reads any video's frames exactly). For the owner: one menu (Ctrl/⌘+Alt+S, or ⋯ in the rail → Capture), files in the captures folder (data/captures: shots, recordings, frames, sheets).
  Screenshots: window, tool (the screen on show), chat, transcript (the whole chat as one tall picture), dock, lab (the Lab preview at its exact frame size), a region / thing the owner drags or clicks; social frames (9:16 1080×1920, 4:5, 1:1, 16:9 and 19 more), clean (no toasts / menus / scrollbars), beautified (gradient, window bar, shadow), annotation (arrows, boxes, text, badges, blur).
  Recording: the hub page's own frame (no OS cursor, no other windows) + Hearth's own sound (mic optional; the whole computer's sound only on Windows), any fps, a tool / region / social frame, pause, markers, countdown, clicks / keys shown; the REC light is a separate window, never in the picture; WebM + MP4 (ffmpeg); opens in Video Review, the editor timeline, or the Lab as media.
  Tours: scripted hands-free recordings, one step per line (record, open, cmd /x, type, click, zoom, caption, title, highlight, wait, stop); /tour steps lists them, /tour intro is a 30 s app intro.
  Frame reader: exact frames by time / frame / timecode (ffprobe's true fps and packet times; VFR safe), every N, scenes, contact sheets, motion curve, pacing, palette, black / frozen / quiet stretches, loudness, letterbox, a color barcode, the best loop. /make (or capture_frames mode make) turns a video into a GIF, a trim, a timelapse, a boomerang, PNG frames for After Effects or a 9:16 / 1:1 / 4:5 copy. Reference footage is for the VIBE (pacing, motion, palette, light), never to reuse unless the owner says so.
  Commands: /shot, /rec (records Hearth anywhere; /record in the Lab records the sketch), /tour, /frames, /captures, /scenes, /contact, /pacing (see /capture-help). Tools (only when the chat opted in with /capture-tools on): capture_shot, capture_record, capture_frames, capture_list.`,
  video: `VIDEO REVIEW (the Video Director's tool): the owner's renders (newest first), a player with A/B compare (wipe, side, onion, difference), timecoded notes with categories, safe zones and crops for socials, contact sheets, ffmpeg export presets (tiktok, reels, shorts, feed45, yt1080…), After Effects renders (aerender) and ExtendScript. Lab recordings land there too. Tools: video_* and ae_*; the owner's notes are in video_status. Its timeline is a full video editor (topic editor).`,
  board: `MOOD BOARD (the "Board" rail tool; Ctrl+Shift+M opens it as a drawer over any chat): the owner's references — pictures, clips, websites (live snapshots), notes, colors, frames — on an infinite canvas, several boards, a board can be linked to a chat.
  REFERENCES GIVE A VIBE, NOT FOOTAGE: take palette, light (key, contrast), color (saturation, warmth), texture (edges, grain), motion energy and cut pacing, composition, type and mood from them; never put the reference media into what you make unless the owner explicitly asks for the clip itself.
  Hearth reads each reference's vibe locally (no tokens) and sends it as short text: the owner drags a reference into the chat, or types /board-use [palette|light|motion|…], /ref <words>, /vibe. Items in a frame named "Avoid" or stamped ✕ are what NOT to do.
  With the board tools (opt-in: /board-tools on): board_list, board_vibe { board?, frame?, item?, focus?, items?, image? }, board_add { kind, text|url|colors…, frame? }, board_arrange { layout, frame? }. A board can carry a brief (the owner's intent, read first) and a default focus. Commands: /board, /board-add <url>, /board-note, /board-layout, /board-lens, /board-template, /board-export (help board lists all).`,
  editor: `THE VIDEO EDITOR (Video Review, E or ✂; any footage, no song needed). The owner makes social videos here (e.g. a motion-design intro for Hearth).
  Model: V1 = the main track (clips play in order; a transition overlaps the cut like xfade), tracks above it (V2, V3… overlays: videos, stills, colors with position / scale / rotation / opacity and blend modes), text tracks (titles, lower thirds and shapes / motion graphics, all with in / out animations), audio tracks (music). A clip has speed, reverse, volume, fades, a look (color grade + adjustments) and keyframes (opacity, x, y in −1…1 of the frame, scale 1 = fit, rotate °, volume) with easing curves. Markers carry notes; I / O set the range that plays and renders. A sequence (seq:<name>) is an edit of its own; templates start one (social-intro-15, app-teaser-15, reel-30…). Formats 9:16, 4:5, 1:1, 16:9 and a frame rate.
  Frame-exact: program frame n starts at n / fps; video_edit_frame { frame } shows it composited and reports the source frame each layer really shows.
  Tools: video_edit_read (the edit as text; what: "presets" + kind: transition, look, title, anim, lower, shape, motion, ramp, format, template, export, easing, blend, adjust), video_edit_frame, video_edit { op } ({ op: "help" } lists ops). Work in small steps, look at frames after visual changes, keep titles inside the safe zone (9:16: the middle 70 % of the height).
  Mood-board references give a vibe (palette, light, texture, motion, pacing, type): never add their media to an edit unless the owner says to use that clip.
  A sequence made in the Lab (topic sequence) has "Lab scene" clips and "Lab layer" overlays: trim, move and transition them like any clip; the Lab draws them (and renders them for the export).
  The owner's chat commands: /editor, /edit-list, /add-title, /lower-third, /add-shape, /transition, /grade, /keyframe, /edit-motion, /speed-ramp, /overlay, /add-music, /edit-format, /edit-template, /goto-frame, /frame-check, /edit-render (help editor).`,
  sequence: `THE LAB SEQUENCE ("▤ Sequence" on the Lab timeline, /sequence): a video built in the Lab from scenes. Main track: scene clips (a sketch / chat scene, its own look or a board vibe, playing on its own clock from the clip's start) and footage clips, with the editor's transitions between them (dissolve by default); tracks: Titles (the editor's styles + animations), Overlays (a layer or filter over a range), Sound (the song: its analysis still drives what reacts; scenes stay time-driven unless the owner asks).
  The preview plays it live, switching / cross-fading scenes in the same page; seek is frame-exact (any scene, any frame). Render = frame by frame at 9:16 / 16:9 / 1:1 / 4:5 with the sound, into Video Review. It is an editor sequence (one model): "editor" opens it there for finishing, "back" brings it to the Lab.
  Tool: three_do { cmd: "sequence", op } — status · add { scene: name | number | "current", at: "bar 9" | seconds | "f120", bars | secs, look } · add { title | footage (path) | overlay (layer / filter) | song } · transition { clip: n, type: dissolve | dip-black | wipe-left | push-left | zoom-in | cut… } (no clip: every cut) · length { clip, bars | secs } · trim { clip, edge, to } · split { at } · delete { clip, ripple } · move { clip, to } · look { clip, name } · fit (cuts on bars) · frame { at } (a picture) · render { format } · editor · back · undo. Clip n = its place on the main track; titles are "Titles.1".
  Defaults need no choices: a scene lasts 4 bars with a song (4 s without), a dissolve between scenes, new scenes fit the bars. Owner's commands: /sequence, /add-scene, /sequence-render.
  Each scene owns its sequence (switching scene / chat switches it; ops act on the director chat's scene; of: another scene). Fewer decisions: arrange { template: music-video | product-intro | teaser | bumper | loop | lyric (lines) | changelog (lines) | reel | mood | drop-showcase, scenes, secs } puts the scenes on the song's sections (cuts on bars, a transition chosen per section change, a scene coming back in another look); again = another arrangement; versions { secs: [15, 6] } = shorter cuts; fill { clip } fills a gap; vary { clip } / vary_sections / swap_looks = per-clip looks; nest { name } = a sequence as a clip; copy / paste { into } across sequences; roll / slide / marker. Lab transitions (only the Lab does them well; the editor bakes them): lab-fly, lab-fly-back (each scene's camera flies), lab-morph (shared layers stay), lab-depth, lab-depth-far, lab-mosh, lab-stutter, lab-match (match cut on the shape), lab-flash-beat, lab-bloom. A scene's own hit markers and cue looks move with its clip, like keyframes. Owner: /arrange, /sequence make | again | versions | fill | vary.`,
  motion: `MOTION DESIGN KIT (for the owner's Hearth intro for socials): ready layers drawn by motion.<kind>(P) in the sandbox, each one node in the Nodes view, every knob a slider (keyframe them). Time-driven from the layer's own start; words land on the song's hit markers / beats only when there is a song.
  Families: Hearth on screen (ui: captures of Hearth or Hearth drawn — mock:chat, mock:lab, mock:board, mock:editor, mock:nodes, mock:jam — as 3D cards / glass panels / laptop, phone, browser, tablet frames; layouts single, stack, parallax, explode, fly-in, carousel, wall, hero, zoom, fan, feed, split, turntable, elements; plus a clicking cursor), kinetic type (33 per-letter animations: type-on, cascade, split, slam, wave, scramble, breathe, word-by-word…, fitted to the frame's safe zone), 3D type, camera moves (dolly, orbit, crane, truck, whip pan, rack focus, handheld, zoom punch, vertigo…: a rig the 3D layers follow, or the whole picture under it), logo reveals (the Hearth flame / Forgeheart anvil: line draw, 3D spin, slam, burst, particles, molten), brand looks (forge gradient, molten, aurora, grid, grain, light sweep, embers…), end cards (name, line, call to action).
  Tool: three_do { cmd: "motion", op } — list { family } · add { preset: "cascade" | "laptop" | "dolly in" | "flame line"…, words, pics: ["hearth-1", "mock:lab"], values: { knob: v }, in, out } (a NEW layer) · hearth { layout, frame, words } (a whole shot: backdrop, screens, cursor, title, camera) · words { layer, text } · set { layer, values } · seq { preset, at, secs } (an overlay on the Lab sequence) · intro (a sample sequence logo → on screen → end card). Pictures of Hearth: capture first (the owner's ◉ Capture or capture_shot), they become the sketch's references. Board references give vibe only. Owner's commands: /motion-kit, /hearth-on-screen, /kinetic, /camera-move, /shot-list, /logo-reveal, /end-card, /brand-look, /motion-words, /motion-seq, /motion-intro.`,
  intro: `VIDEO PROJECTS (/intro; the owner's real job: a motion-design video presenting Hearth for socials, made with the chats). One project ties together: a plan (beats, length, formats 9:16 / 16:9 / 1:1 / 4:5, a beat template), the linked mood board's vibe (palette, light, motion, moods: never its footage), Lab scenes (Claude ⇄ Astra jam one per "lab" beat, each its own sketch), captures (Hearth's own UI filmed by capture tours, one recipe per area: chats, lab, board, editor, jam, capture…; the Lab recorded at the main format), one sequence in the video editor (titles, transitions, grade, music cut on the bars, a marker per beat), a frame-exact review (each beat's frames checked, a contact sheet, review notes as markers) and renders in every format with a cover each.
  It runs as steps (plan → vibe → scenes → captures → edit → review → render), shown in one card in the chat; each step is an undo point, any beat can be redone alone, Claude and Astra take over each other's step (/intro handoff).
  You drive it with video_edit { op: "project", action }: status · plan · task (the handoff text) · beat { beat, words | secs | films (a tour recipe) | idea } · redo { beat } · run { step } · cover { mode: best|hook|lab|end|middle } · cuts { secs: [15, 6] } (shorter cuts from the same captures) · note { text }. Then polish the edit itself with video_edit / video_edit_frame (it is an ordinary sequence).
  Kinds of beat: title (words on a color), lab (a jammed Lab scene), tour (Hearth on screen), shot (a still with a push), stat (a number counted from the app), end (name + line + call to action). The owner's commands: /intro, /intro go, /intro decide (Astra picks the details), /intro status, /intro redo <beat>, /cut-downs 15 6, /post-text tiktok, /film <recipe>, /video-projects.`,
  comp: `COMP (precomps, like After Effects): a precomp is a layer of your scene whose content is ANOTHER scene (another chat's, a sketch, or a Lab sequence), live: when that chat's director edits its scene, the layer here changes too. It has its own clock (start: the scene second it starts at, speed, offset, loop or hold; time remap keys = scene s → its s), the usual layer settings (x / y / scale / rotate / opacity / blend / in / out / fades, keyframable) and its own crop [t, r, b, l] %, mask (rounded, circle, ellipse), soft edge, effects (blur, bright, contrast, sat, hue, gray, invert, sepia) and resolution. Filter layers above it work on it. Precomps nest; a scene can't hold itself.
  Tool: three_do { cmd: "comp", op } — list · add { source: chat title | sketch name | "seq:<name>", layout: full | pip | left | right | top | bottom | q1-q4 | circle } · set { layer, … } · key { layer, property: remap | cropT… | blur… | x | scale…, keys: [{ time, value, ease }] } · remove · render { format } (frame by frame).
  Parts at once: dispatch { parts: [{ brief, engine: claude | astra, name }], layout: time (one after the other, default) | split (side by side) | stack } gives each part its own director chat and scene, all working at once (each gets only its brief); they show here as precomps. parts (status: working / waiting / done / stuck, what each said) · feedback { part, text } · again { part, fresh } · swap { part } (Claude ⇄ Astra). Split a video into parts when the owner asks for one made by several agents; check parts, give feedback, then render.
  The owner: /comp, /dispatch a | astra: b | c, Alt+C in the Lab, right-click a layer → ◫ Precomp.`,
  chats: `CHATS (round 9): what your tool calls make shows under your reply as cards the owner opens, scrubs and drags to the board, the editor or another chat (captures and renders as files, Lab frames you looked at, the scene you changed, a sequence, a board item, a video project). Hearth draws them from its own record of your calls: you don't need to describe or link files; name what you made in a few words.
  Each chat remembers the board, scene, sequence, video project, captures and renders it worked with. When the owner's words point at one ("use the board", "render it again", "the last capture"), the message ends with one line like [Hearth context: board "Neon" (linked to this chat); Lab sequence "Intro"; last video /path.mp4]: that is what "it" means; use your tools on it (and a board vibe attached as <file name="vibe · …"> is a vibe, never footage). Chats continued on the other engine (handoff, continue with) keep the same context.`,
};

const LINE = (helpCall) => `HEARTH (the owner's app: Claude and Astra chats, the Lab, Video Review, chat commands): Claude and Astra share this chat, its scene and the task state Hearth keeps. Map: ${helpCall} app|lab|nodes|react|commands|handoff|habits.`;

const ALIAS = { precomp: 'comp', precomps: 'comp', compositing: 'comp', dispatch: 'comp', parts: 'comp', kinetic: 'motion', typography: 'motion', motiondesign: 'motion', ui: 'motion', mockup: 'motion', devices: 'motion', endcard: 'motion', logo: 'motion', logos: 'motion', brand: 'motion', camera: 'motion', cameramoves: 'motion', shots: 'motion', shotlist: 'motion', seq: 'sequence', montage: 'sequence', storyboard: 'sequence', hearth: 'app', overview: 'app', program: 'app', map: 'app', model: 'lab', graph: 'nodes', node: 'nodes', reactive: 'react', reactivity: 'react', command: 'commands', cmds: 'commands', slash: 'commands', task: 'handoff', switch: 'handoff', engines: 'handoff', astra: 'handoff', claude: 'handoff', rules: 'habits', conventions: 'habits', review: 'video', renders: 'video', moodboard: 'board', boards: 'board', refs: 'board', references: 'board', vibe: 'board', footage: 'capture', frames: 'capture', record: 'capture', recording: 'capture', screenshot: 'capture', screenshots: 'capture', tour: 'capture', tours: 'capture', edit: 'editor', edits: 'editor', nle: 'editor', cut: 'editor', titles: 'editor', transitions: 'editor', project: 'intro', projects: 'intro', social: 'intro', socials: 'intro', promo: 'intro', teaser: 'intro', beats: 'intro', cutdowns: 'intro', chat: 'chats', cards: 'chats', context: 'chats', attach: 'chats', attachments: 'chats' };

// topic → text, or null when it isn't a map topic
function topic(name) {
  const t = String(name || '').toLowerCase().replace(/[^a-z]/g, '');
  const key = TOPICS[t] ? t : ALIAS[t];
  return key ? TOPICS[key] : null;
}

module.exports = { TOPICS, LINE, topic, ALIAS };
