// MCP server for the Three Director: Claude writes and runs three.js sketches in the hub's Lab
// from the user's descriptions, checks the console and looks at the result.
const { serve } = require('./common');

const GUIDE = `The user describes scenes in words; you build them as three.js sketches in the hub's Three.js Lab, which they watch live next to this chat. Most of what they make are music visualizers for short videos.
Sketches are ES modules: import * as THREE from 'three' and addons from 'three/addons/...' (e.g. 'three/addons/controls/OrbitControls.js', 'three/addons/postprocessing/EffectComposer.js'). Create your own WebGLRenderer, append renderer.domElement to document.body, size it to innerWidth/innerHeight, handle resize, and animate with renderer.setAnimationLoop((now) => …) (time in ms). Don't use THREE.Clock (deprecated).
Tuning without code: three_sliders moves a layer's sliders (unsaved, the user keeps or undoes them) and three_looks saves / applies looks; for "show me variations", set sliders, save each as a look, show it with chat_show, then ask with chat_ask. Whole-piece check: three_contact_sheet shows a frame at every cue in one image (use it when you review a music visualizer). Workflow: three_set_code with a complete sketch → read the console/errors it returns → three_screenshot to see the result → refine. Keep going until it matches the request.

LAYERS: a sketch is a stack of layers, like in Photoshop or After Effects. Each layer is its own complete sketch module (own WebGLRenderer, scene, camera and tweak() sliders); the Lab stacks them in the preview (bottom first) with each layer's opacity, blend mode, position/scale/rotation, and the time range when it plays (in/out on the song, with fades). The user sees a layers panel and a track per layer under the song timeline.
  - three_get_code / three_set_code work on the SELECTED layer. Use three_layers to see them, three_select_layer to switch.
  - SCENE EDITOR: the user can fly around a layer's scene and drag objects into place (✥ Edit scene). Those placements are kept outside the code and re-applied every frame; three_layers shows them as placedByUser (by object name '#name', or child index path, '@camera' = the view they framed). Give important objects a .name so placements stay attached to them. When asked to bake placements, write them into the code with three_edit_code.
  - LIVE SOUND: the user can make sketches react to what the computer plays (Spotify, YouTube…) or a mic (🎧 Live). Then audio.live is 'system' or 'mic', audio.level / bass / mid / treble / spectrum / waveform are live, audio.kick / snare / beat come from attacks detected in the sound, and there is no song timeline (audio.time is the clock). The tempo is found from the kicks after a few seconds: audio.bpm, audio.beatPhase, beatInBar and barPhase then follow the music (audio.bpm is 0 until then). Levels are auto-levelled, so don't over-boost them. three_media_info → live tells you the input, the tempo and what's playing (Spotify title / artist / album): use it when the user says "make it fit this song". Sketches written with the audio globals work in both cases.
  - GAMES / INTERACTIVE SKETCHES: three_eval runs JavaScript inside the live preview and returns the value (three.js objects summarized). __scenes['Layer name'] gives { scene, camera, renderer } of each layer, so you can inspect what exists right now (e.g. __scenes['World'].scene.getObjectByName('wall1').userData). Variables inside a layer's module aren't global: expose game state as window.game = { … } in the code you write so you can read it. three_input presses keys (hold for ms), clicks or moves the mouse in the preview, with screenshot: true to see the result: play-test instead of guessing.
  - BIG CODE: layers over 350 lines come back as an outline with line numbers. Read any part with three_read_code (layer, from, to), find things across all layers with three_search_code, and change code with three_edit_code (exact find → replace edits, or replace a line range) instead of rewriting a whole layer. Prefer three_edit_code for small changes to any layer: it is faster and can't lose code you didn't see.
  - "add another layer with …" → three_add_layer with complete code. Upper layers must be transparent: new THREE.WebGLRenderer({ alpha: true, antialias: true }), NO scene.background and no setClearColor, so the layers below show through (the bottom layer may have a background). Add, screen or lighten blend modes make glowing layers look great on top.
  - "only during the drop", "fade it in", "make it softer", "move it up", "put it behind" → three_update_layer with settings { in, out, fadeIn, fadeOut, opacity, blend, x, y, scale, rotate, visible, name } and/or order ("top", "bottom" or a number, 1 = bottom). Times are seconds on the song (use the user's grid, markers, drops and loop from three_media_info).
  - "remove that layer" → three_remove_layer (the user can undo it).
  - Filter layers (like adjustment layers) restyle everything below them: three_add_layer with template "ascii", "datamosh", "vhs" (found footage / camcorder with REC timecode), "glitch", "crt", "pixelate", "halftone", "film", "kaleido", "edges" (neon outlines), "thermal", "duotone" or "glow". Their settings are normal tweak() sliders (change them with three_update_layer code, or animate them with three_keyframes); the layer's opacity mixes the effect with the original, its in/out times limit it to a part of the song (e.g. glitch only on the drop), and its order decides what it affects (only layers below it).
  - Keyframes (like After Effects): three_keyframes animates a layer's opacity, x, y, scale, rotate, or any of its tweak() sliders (numbers and '#rrggbb' colors) over the song: keys [{ time, value, ease }] with ease "ease" (default), "linear" or "hold". "Fade the glow up into the drop", "zoom in over the build", "turn it red on the drop" → keyframes on the right property, timed with the user's grid, markers and drops. Keyframed values override the slider/setting while they exist.
  - Automation lanes: under each layer's track the user can show several settings' curves at once (FL Studio-style points and curve handles, Ableton-style placement). Keys from three_keyframes appear there too; a key can have ease "curve" with c in -1..1 (the bend). three_timeline_edit { lane: { layer, property } } adds a lane for the user ({ show: false } removes it, property "all" shows every animated one, property null hides them all).
  - Animation presets (three_animate): fadeIn, fadeOut, popIn, slideLeft, slideRight, slideUp, slideDown, zoom, spin, pulse (every beat), shake (on kick markers), blink (on snare markers), over the layer's time (or the loop, or the whole song).
  - TIMELINE: three_timeline reads the grid (BPM, downbeat), kick/snare/hit markers, the user's named cues (song sections), loop, zoom, every layer's time range, keyframes and lane, and the user's notes. three_timeline_edit sets the grid ("auto" or { bpm, downbeat, beatsPerBar }), adds / removes / clears markers ({ add: { kick: [seconds] }, remove, clear: ['snare'], range: [start, end] }), the loop, the zoom, and which lane shows. Prefer the user's own grid and markers; only change them when they ask.
  - REFERENCES: the user's own files for this sketch (pictures, logos, video clips, 3D models, sounds, fonts, data). three_references list shows them (and the pictures themselves). In code: refTexture('name') returns a THREE texture for an image or video (videos play muted and looping); refs.name is a URL for any loader (GLTFLoader for .glb, fetch for json/csv, FontFace, new Audio). Files the user drops in this chat that aren't pictures are added automatically (a note tells you the name). A picture attached in the chat is only shown to you: when the user wants it IN the scene (texture, logo, background, particles from its colors), add it with three_references { action: "add", path: <its attachment path> } first. Never guess file names: list them. The sketch can also have a palette (the global palette = ['#rrggbb', …], often taken from a reference picture): use it for colors when it's set, and set it with three_references { action: "palette", from: <picture name> } or { colors: [...] } when the user asks for colors from a picture.
  - CUE LOOKS: a cue (song section) can carry slider looks (three_timeline → cues[].looks = [{ layer, name }]): while the song plays, each layer morphs into the look of the last cue that set one for it. Save looks with three_sliders / looks so the user can pin them to cues (right-click a cue → ✦ Look at this cue), or set them yourself: three_timeline_edit { cues: { add: [{ time: <the cue's time>, looks: [{ layer: 'Layer name', name: 'Look name' }] }] } } (an existing cue at that time keeps its name and gets the looks).
  - NOTES: the user pins notes on moments (a time, a screenshot and what to change). three_notes list returns them with the open notes' screenshots; after making a change, mark that note done (action "done", id). You can add notes for things you want the user to look at.
  - Inside a layer's code, the global "layer" gives { name, time (seconds since the layer starts), progress (0..1 over its time range), mix } for intros/outros.
  - Layers are separate pictures stacked on top of each other: objects can overlap visually, but one layer can't hide behind another layer's object in 3D. Put things that must intersect in the same layer.

FRAME: the user picks the output size with buttons (Fit, 9:16 = 1080×1920, 16:9, 1:1, 4:5); reports tell you the current "frame". In exact sizes innerWidth/innerHeight ARE the output pixels and devicePixelRatio is 1. Compose for that frame (vertical 9:16: keep the subject in the middle, away from the top 12% and bottom 22% where Shorts/TikTok put titles and captions). You can switch it with three_set_frame when they ask for a format.

SLIDERS (always): every sketch must expose its main settings as clearly named sliders with the global tweak() helper, near the top of the code. The user does not write code; sliders are how they shape the result, so make them understandable:
  const P = tweak({
    style:      { value: 'rings', options: ['rings', 'bars', 'particles'], label: 'Visual style', group: 'Look' },
    bassPunch:  { value: 1.2, min: 0, max: 3, label: 'Bass punch', group: 'Music', hint: 'How hard shapes jump on kicks' },
    smoothing:  { value: 0.6, min: 0, max: 0.95, label: 'Smoothing', group: 'Music', hint: 'Higher = calmer, slower reactions' },
    glowColor:  { value: '#ff3cac', label: 'Glow color', group: 'Color' },
    spin:       { value: 0.3, min: -2, max: 2, label: 'Spin speed', group: 'Motion' },
    bloom:      { value: 1.1, min: 0, max: 3, label: 'Glow strength', group: 'Look' },
    showGrid:   { value: false, label: 'Floor grid', group: 'Look' },
  });
  Shorthand also works: name: [value, min, max] or [value, min, max, step], '#rrggbb' for colors, true/false for switches.
  Use 6–12 controls in groups like Music, Motion, Shape, Color, Camera, Look; plain-language labels; a hint when the effect isn't obvious; sensible min/max (the full range should still look OK); options lists for styles/modes.
  Read P.x every frame (in the animation loop) so moving a slider changes the scene instantly, e.g. mat.color.set(P.glowColor); bloomPass.strength = P.bloom. Things that need rebuilding (counts, geometry detail, a style switch that creates different objects) can be read at setup: the Lab re-runs the sketch automatically as the user drags. For expensive rebuilds you can also use { value, min, max, onChange: (v) => … }.
  The user can also link any number slider to the music themselves (♪ button), so prefer clean base values over hard-coding the reactivity amount.

MUSIC: the user loads an mp3/mp4 in the Lab (or you load one with three_load_media). Sketches read it through globals:
  audio.bass / audio.mid / audio.treble / audio.level  — 0..1 right now
  audio.beat     — 1 on each beat, fading to 0 (~150 ms), from the Lab's beat tracker
  audio.spectrum — Uint8Array(1024) FFT magnitudes (0..255), audio.waveform — Float32Array(2048), -1..1
  audio.band(lowHz, highHz) — 0..1 average of any range (e.g. audio.band(40, 90) for kicks)
  audio.time / audio.duration / audio.playing / audio.bpm
  audio.kick / audio.snare / audio.hit — 1 exactly on the user's hand-placed markers, fading over ~120 ms. The user marks kicks, snares and hits by hand because edits hit on those: when a track has markers (three_media_info → hits), drive cuts, flashes, camera jumps and punches from these, not from audio.bass/beat guesses.
  audio.trigger('kick' | 'bass' | 'snare' | 'hats' | 'hit') (and audio.hats, audio.triggers) — 1 when that sound fires, fading over ~120 ms. They come from the user's hand-placed markers when the song has some, otherwise from the user's ⚡ Triggers (a frequency band + a level bar each, set on an EQ-style view; three_triggers). Prefer them over thresholding audio.bass yourself: the user tunes them by ear.
  HELPERS: audio.energy (loudness over ~1 s, calm vs intense), audio.cue ({ name, index, start, end, progress } of the user's named section, e.g. if (audio.cue?.name === 'Drop')), audio.untilDrop / audio.sinceDrop (seconds), onHit('kick' | 'snare' | 'hit' | 'hats' | 'bass' | 'beat', (strength) => …) runs once per hit, damp(current, target, speed, dt) frame-rate-independent smoothing, ease.inOutCubic / outBack / outElastic / outBounce… (t 0..1), noise(x, y, z) smooth Perlin noise (-1..1), seeded(n) a repeatable random(); clamp, mix, map(v, a, b, c, d), smoothstep, fract, pingpong, snap(v, step), wave(t, speed); hsl(h, s, l) and paletteAt(t) colors ('#rrggbb', paletteAt blends along the user's palette); beatPulse(div) (1 on each beat / eighth / sixteenth); onBar(fn), onCue(fn) (the user's sections), everyBeats(n, fn); audio.peak (loudest of the last 3 s), audio.section ('quiet' | 'medium' | 'loud'). Use them instead of re-writing your own.
  audio.hits — { kick: [seconds], snare: [...], hit: [...], bass: [...], hats: [...] } (bass / hats rows exist when the user wrote them from ⚡ Triggers → Timeline; they then drive audio.bassHit / audio.hats); audio.since('kick') / audio.next('snare') — seconds since the last / until the next ('beat' works too), e.g. to anticipate a hit.
  audio.beatInBar (1..beatsPerBar), audio.bar (1..), audio.beatPhase / audio.barPhase (0..1), audio.beatsPerBar — from the user's beat grid (BPM + downbeat set like in rekordbox) when they set one.
  audio.analysis — the whole track: { bpm, beats: [seconds], drops: [seconds], sections: [{ start, end, energy: 'quiet'|'medium'|'loud' }], fps: 30, level/bass/mid/treble: [0..1 per 1/30 s] } so you can anticipate drops: e.g. const loud = audio.analysis?.sections?.find(s => audio.time >= s.start && audio.time < s.end)?.energy === 'loud'.
  media.video / media.texture() — for an mp4, the playing video element and a THREE.VideoTexture of it.
  Without a file, audio gives a soft 120 bpm demo beat (audio.simulated = true), so always design so it still looks good.
  Smooth the raw values yourself (e.g. lerp toward them with the Smoothing slider) and scale them with sliders. Use three_media_info to learn the track (the user's grid and hit markers, drops, quiet/loud sections) and three_media_control to jump to a hit or drop before taking a screenshot.`;

const TOOLS = [
  { name: 'three_get_code', description: 'The selected layer of the current sketch (name, code), the list of layers, frame size, named sliders with their current values (and music links), and any slider changes the user has not saved.', inputSchema: { type: 'object', properties: {} } },
  { name: 'three_set_code', description: 'Replace the code of the selected layer (the whole sketch when it has one layer) with complete code and run it. Returns console output, errors (with line numbers), performance stats, the frame size, the sliders it found and the loaded music. The previous code is kept in the sketch history.',
    inputSchema: { type: 'object', properties: { code: { type: 'string' }, wait: { type: 'number', description: 'Seconds to let it run before reporting (default 2.5)' } }, required: ['code'] } },
  { name: 'three_new_sketch', description: 'Create a new named sketch with this code, open it and run it (keeps the user\'s other sketches untouched).', inputSchema: { type: 'object', properties: { name: { type: 'string' }, code: { type: 'string' } }, required: ['name', 'code'] } },
  { name: 'three_screenshot', description: 'Image of what the sketch shows right now (at the current frame size).', inputSchema: { type: 'object', properties: {} } },
  { name: 'three_console', description: 'Recent console lines and errors from the running sketch, plus fps/draw-call stats, sliders, frame size and music.', inputSchema: { type: 'object', properties: {} } },
  { name: 'three_triggers', description: 'The user\'s ⚡ Triggers: which band of the sound fires audio.kick / bass / snare / hats / hit (for songs without hand-placed markers, and live sound). Without set: returns them. set: { hats: { lo, hi, thr, gap, on } } changes some (lo / hi in Hz, thr = the bar 0..1, gap = shortest ms between triggers). Change them only when the user asks (e.g. "the hats fire too often").',
    inputSchema: { type: 'object', properties: { set: { type: 'object' } } } },
  { name: 'three_media_info', description: 'The music/video loaded in the Lab: file, duration, tempo (bpm), beat count, drops, quiet/medium/loud sections and the energy of bass/mids/highs every 5 seconds, plus the playhead.', inputSchema: { type: 'object', properties: {} } },
  { name: 'three_load_media', description: 'Load an audio or video file (mp3, wav, m4a, mp4, mov, webm…) from the user\'s computer into the Lab by absolute path, analyze it and return the same info as three_media_info.', inputSchema: { type: 'object', properties: { path: { type: 'string' } }, required: ['path'] } },
  { name: 'three_media_control', description: 'Play, pause or jump in the loaded music (e.g. seek to a drop, play, then take a screenshot), or set the A–B loop the user works on (action "loop" with time = start and end; no time clears it). The user can lock their loop; then leave it alone.', inputSchema: { type: 'object', properties: { action: { type: 'string', enum: ['play', 'pause', 'seek', 'loop'] }, time: { type: 'number', description: 'Seconds: where to seek, or the loop start' }, end: { type: 'number', description: 'Loop end in seconds' } }, required: ['action'] } },
  { name: 'three_layers', description: 'The layers of the current sketch (bottom first): names, which one is selected, visibility, opacity, blend mode, when each plays on the song, transform, and their sliders.', inputSchema: { type: 'object', properties: {} } },
  { name: 'three_add_layer', description: 'Add a layer (on top unless position says otherwise), select it and run it. Give complete code for a transparent layer (renderer with alpha: true, no scene.background), or a template: "empty" (a shape that pumps on kicks), "rings", "particles".',
    inputSchema: { type: 'object', properties: { name: { type: 'string', description: 'Short name the user will recognize, e.g. "Particles", "Glow rings"' }, code: { type: 'string' }, template: { type: 'string', enum: ['empty', 'rings', 'particles', 'ascii', 'datamosh', 'vhs', 'glitch', 'crt', 'pixelate', 'halftone', 'film', 'kaleido', 'edges', 'thermal', 'duotone', 'glow'], description: 'Scene templates: empty, rings, particles. Filters (change everything below the layer): ascii, datamosh, vhs (found footage), glitch, crt, pixelate, halftone, film, kaleido, edges, thermal, duotone, glow.' }, position: { description: '"top" (default), "bottom" or a number (1 = bottom)' }, settings: { type: 'object', description: 'Optional layer settings: in, out, fadeIn, fadeOut, opacity, blend, x, y, scale, rotate, visible' }, wait: { type: 'number' } } } },
  { name: 'three_update_layer', description: 'Change a layer: its settings (in/out seconds on the song or null for the whole song, fadeIn/fadeOut seconds, opacity 0..1, blend: normal|add|screen|lighten|overlay|soft-light|multiply|darken|difference|exclusion|color-dodge, x/y in % of the frame, scale, rotate in degrees, visible, name), its stacking order, and/or its code (complete module). Returns errors and stats like three_set_code.',
    inputSchema: { type: 'object', properties: { layer: { description: 'Layer name, id, number (1 = bottom), "top", "bottom" or "selected"' }, settings: { type: 'object' }, order: { description: '"top", "bottom" or a number (1 = bottom)' }, code: { type: 'string' }, wait: { type: 'number' } }, required: ['layer'] } },
  { name: 'three_keyframes', description: 'Animate a property of a layer over the song with keyframes (replaces that property\'s keyframes; clear: true removes them). property: opacity (0..1), x / y (% of the frame), scale, rotate (degrees), or a slider of the layer by its key or label (number, or "#rrggbb" for colors).',
    inputSchema: { type: 'object', properties: { layer: { description: 'Layer name, id, number, "top", "bottom" or "selected"' }, property: { type: 'string' }, keys: { type: 'array', items: { type: 'object', properties: { time: { type: 'number', description: 'Seconds on the song' }, value: {}, ease: { type: 'string', enum: ['ease', 'linear', 'hold'] } }, required: ['time', 'value'] } }, clear: { type: 'boolean' } }, required: ['layer', 'property'] } },
  { name: 'three_timeline', description: 'The song timeline: grid (BPM, downbeat), kick / snare / hit markers, loop, zoom, every layer\'s time range, keyframes and shown automation lanes, and the user\'s notes. Optional from / to (seconds) limits the markers.', inputSchema: { type: 'object', properties: { from: { type: 'number' }, to: { type: 'number' } } } },
  { name: 'three_timeline_edit', description: 'Change the timeline: grid ("auto" or { bpm, downbeat (seconds of a bar\'s beat 1), beatsPerBar }), markers ({ add: { kick: [s], snare: [s], hit: [s] }, remove: {…}, clear: ["kick"…], range: [start, end], snap: true }), loop ({ start, end } or null), zoom ({ start, end } or null for the whole song), cues (named hot cues like "Drop": { add: [{ time, name }], remove: [name or time], clear: true }), speed (playback 1, 0.75, 0.5 or 0.25), lane ({ layer, property, show } adds that setting\'s automation lane under the layer (show: false removes it; property "all" = every animated one; null hides them all)). Only change the user\'s grid / markers when they ask.',
    inputSchema: { type: 'object', properties: { grid: {}, markers: { type: 'object' }, loop: {}, zoom: {}, lane: { type: 'object' }, cues: { type: 'object' }, speed: { type: 'number' } } } },
  { name: 'three_animate', description: 'Apply a one-click animation preset to a layer (adds keyframes over the layer\'s time, or the loop, or the whole song): fadeIn, fadeOut, popIn, slideLeft, slideRight, slideUp, slideDown, zoom, spin, pulse (every beat), shake (kick markers), blink (snare markers).',
    inputSchema: { type: 'object', properties: { layer: { description: 'Layer name, id, number, "top", "bottom" or "selected"' }, preset: { type: 'string', enum: ['fadeIn', 'fadeOut', 'popIn', 'slideLeft', 'slideRight', 'slideUp', 'slideDown', 'zoom', 'spin', 'pulse', 'shake', 'blink'] } }, required: ['layer', 'preset'] } },
  { name: 'three_notes', description: 'The user\'s notes on moments of the song (time, screenshot, what to change). action "list" (default) returns them plus the open notes\' screenshots; "done" / "reopen" / "edit" (text) / "delete" take an id; "add" takes time and text (a screenshot is taken).',
    inputSchema: { type: 'object', properties: { action: { type: 'string', enum: ['list', 'done', 'reopen', 'edit', 'delete', 'add'] }, id: { type: 'string' }, time: { type: 'number' }, text: { type: 'string' } } } },
  { name: 'three_references', description: 'The user\'s reference files for the open sketch (images, videos, 3D models, sounds, fonts, data). action "list" (default) returns names, kinds and how to use each in code, plus the pictures; "add" takes path (a file the user attached in this chat) and optional name; "rename" takes name and to; "remove" takes name; "palette" sets the sketch palette from a picture (from: name), a list (colors: [\'#rrggbb\'…]) or a Coolors link (coolors: \'https://coolors.co/palette/…\'). In code: refTexture(\'name\') for images / videos, refs.name (URL) for anything else.',
    inputSchema: { type: 'object', properties: { action: { type: 'string', enum: ['list', 'add', 'rename', 'remove', 'palette'] }, path: { type: 'string' }, name: { type: 'string' }, to: { type: 'string' }, from: { type: 'string' }, colors: { type: 'array', items: { type: 'string' } }, coolors: { type: 'string' } } } },
  { name: 'three_sliders', description: 'Read or move the named sliders of a layer (default: the selected one) without changing its code, like the user dragging them: set { key: value } (numbers, \'#rrggbb\', true/false or an option). The user sees the changes as unsaved and can Save, undo or compare (A/B). Locked sliders are skipped. Returns the sliders and saved looks.',
    inputSchema: { type: 'object', properties: { layer: { description: 'Layer name, id, number, "top", "bottom" or "selected"' }, set: { type: 'object' } } } },
  { name: 'three_looks', description: 'Looks are saved sets of slider values the user switches between with one click. action "list" (default), "save" (the current values as name), "apply" (name) or "delete" (name).',
    inputSchema: { type: 'object', properties: { action: { type: 'string', enum: ['list', 'save', 'apply', 'delete'] }, name: { type: 'string' }, layer: {} } } },
  { name: 'three_contact_sheet', description: 'One image with a frame at each of the user\'s cues (or evenly over the loop / whole song, count frames, or at the given times in seconds), numbered and labeled with times. Use it to judge the whole piece (intro → drop → outro) instead of a single screenshot, e.g. when you review your work.',
    inputSchema: { type: 'object', properties: { times: { type: 'array', items: { type: 'number' } }, count: { type: 'number' } } } },
  { name: 'three_remove_layer', description: 'Remove a layer from the sketch (the user can undo it from the toast).', inputSchema: { type: 'object', properties: { layer: { description: 'Layer name, id, number, "top", "bottom" or "selected"' } }, required: ['layer'] } },
  { name: 'three_eval', description: 'Run JavaScript inside the running sketch and get the result (an expression, or statements with return; await works). __scenes[layer name] = { scene, camera, renderer }; window.game etc. if the code exposes them. three.js objects come back summarized (type, name, position, children…).',
    inputSchema: { type: 'object', properties: { code: { type: 'string' } }, required: ['code'] } },
  { name: 'three_input', description: 'Play-test: press keys and click inside the preview. actions in order: { key: "ArrowLeft", ms: 400 } holds a key, { keys: ["w", "Shift"], ms } holds several, { click: [x, y] } with x, y from 0 to 1 across the view, { move: [x, y] }, { wait: ms }. screenshot: true returns a picture afterwards.',
    inputSchema: { type: 'object', properties: { actions: { type: 'array', items: { type: 'object' } }, screenshot: { type: 'boolean' } }, required: ['actions'] } },
  { name: 'three_read_code', description: 'Read part of a layer\'s code with line numbers (default: the selected layer, lines 1–250). Use from / to to read further.',
    inputSchema: { type: 'object', properties: { layer: { description: 'Layer name, id, number, "top", "bottom" or "selected"' }, from: { type: 'number' }, to: { type: 'number' } } } },
  { name: 'three_search_code', description: 'Find text (or a regex with regex: true) in every layer\'s code (or one layer). Returns each match with its layer, line number and context lines.',
    inputSchema: { type: 'object', properties: { pattern: { type: 'string' }, layer: {}, regex: { type: 'boolean' }, context: { type: 'number' } }, required: ['pattern'] } },
  { name: 'three_edit_code', description: 'Change part of a layer\'s code and re-run it: edits [{ find: exact text, replace }] (find must match once unless all: true; whitespace counts) or [{ lines: [from, to], replace }] to replace a line range (read it first). Edits apply in order. Returns errors / console like three_set_code.',
    inputSchema: { type: 'object', properties: { layer: {}, edits: { type: 'array', items: { type: 'object', properties: { find: { type: 'string' }, replace: { type: 'string' }, all: { type: 'boolean' }, lines: { type: 'array', items: { type: 'number' } } } } }, wait: { type: 'number' } }, required: ['edits'] } },
  { name: 'three_select_layer', description: 'Select a layer: three_get_code / three_set_code then work on it. Returns its code.', inputSchema: { type: 'object', properties: { layer: { description: 'Layer name, id, number, "top", "bottom"' } }, required: ['layer'] } },
  { name: 'three_set_frame', description: 'Set the preview/output frame: "fit" (any size), "9:16" (1080×1920, Shorts/Reels/TikTok), "16:9" (1920×1080), "1:1" (1080×1080) or "4:5" (1080×1350).', inputSchema: { type: 'object', properties: { size: { type: 'string', enum: ['fit', '9:16', '16:9', '1:1', '4:5'] } }, required: ['size'] } },
];

serve({ name: 'three-lab', instructions: GUIDE, tools: TOOLS });
