// The FX pack's presets for the Three.js Lab: palettes, looks (colors + filter layers), blend presets and
// keyframe eases. ThreeFX (tools/three-fx.js) shows them in its picker; /palette, /look-apply… use them.
const ThreeFXData = (() => {
  // ---------- palettes: [name, category, 'hex hex hex hex hex'] ----------
  const PAL = [
    // Forgeheart
    ['Forgeheart', 'Forgeheart', 'ffd75e ff8c42 bd8bff ff6a6a 48ddff'],
    ['Forge ember', 'Forgeheart', '1a0b05 5c1a0b c2410c ff8c42 ffd75e'],
    ['Anvil night', 'Forgeheart', '0b0d12 1f2430 3a4050 ffd75e ff6a2a'],
    ['Rune violet', 'Forgeheart', '0d0614 2b1255 6b2fd6 bd8bff f3e8ff'],
    ['Molten core', 'Forgeheart', '2b0000 7a0a00 ff3c00 ffa600 fff1b8'],
    ['Spark & steel', 'Forgeheart', '101418 3b4652 9aa5b1 ffd75e ff8c42'],
    ['Hearth glow', 'Forgeheart', '1b0f0a 4a2412 b5541f f2a65a ffe3b3'],
    ['Arcane forge', 'Forgeheart', '0a0a1f 3d1d7a 7c5cff ff6a6a ffd75e'],
    ['Quench blue', 'Forgeheart', '05101a 0e3a5a 48ddff ffd75e ffffff'],
    ['Slag & gold', 'Forgeheart', '16130f 3a332b 7a6a52 c9a227 ffd75e'],
    // Neon / club
    ['Synthwave', 'Neon', '120024 2d0b59 ff2bd6 2bd9ff ffd75e'],
    ['Cyberpunk', 'Neon', '0b0221 3b0d63 f107a3 00f0ff fcee0a'],
    ['Miami', 'Neon', '0b1e3f ff2a6d d1f7ff 05d9e8 ff9a3c'],
    ['Tokyo night', 'Neon', '1a1b26 7aa2f7 bb9af7 f7768e e0af68'],
    ['Acid rave', 'Neon', '000000 39ff14 ff00ff 00ffff ffff00'],
    ['Laser show', 'Neon', '05010a 00ff9c ff2bd6 2b6bff ffffff'],
    ['Vaporwave', 'Neon', 'ff71ce 01cdfe 05ffa1 b967ff fffb96'],
    ['Blacklight', 'Neon', '0d001a 3c00ff a100ff ff00c8 00ffd5'],
    ['Club red', 'Neon', '0a0000 3d0000 ff0033 ff6a6a ffffff'],
    ['Ultraviolet', 'Neon', '0c0032 190061 240090 3500d3 ff2bd6'],
    ['Hologram', 'Neon', 'a0f0ff c3a6ff ffb3f0 fff3b0 ffffff'],
    ['Glitch RGB', 'Neon', '000000 ff0000 00ff00 0000ff ffffff'],
    // Sunset / warm
    ['Sunset', 'Warm', '2b1055 7f2c7f d8436e f68a5b ffd27a'],
    ['Golden hour', 'Warm', '3d2c1e 8a5a2b d99a4e f4c27a fff0c9'],
    ['Desert', 'Warm', '3b2414 8c5a2e d9a066 f2d0a4 fff4e0'],
    ['Peach', 'Warm', 'ffb4a2 ffcdb2 e5989b b5838d 6d6875'],
    ['Autumn', 'Warm', '582f0e 7f4f24 936639 a68a64 b6ad90'],
    ['Paprika', 'Warm', '2d0c0c 8c1c13 bf4342 e7d7c1 a78a7f'],
    ['Lava', 'Warm', '0d0000 5a0001 b80c09 ff5e00 ffb100'],
    ['Terracotta', 'Warm', '6b2d1a a44a3f d1785c e8b298 f5e3d3'],
    ['Firelight', 'Warm', '03071e 370617 9d0208 e85d04 ffba08'],
    ['Honey', 'Warm', '432818 99582a bb9457 ffe6a7 fff4d6'],
    // Cool / ocean
    ['Ocean', 'Cool', '03045e 0077b6 00b4d8 90e0ef caf0f8'],
    ['Arctic', 'Cool', '0b132b 1c2541 3a506b 5bc0be e0fbfc'],
    ['Deep sea', 'Cool', '001219 005f73 0a9396 94d2bd e9d8a6'],
    ['Glacier', 'Cool', 'e8f1f2 b3d4e0 6fa8c7 2f6690 0f2d4a'],
    ['Midnight', 'Cool', '020202 0d1b2a 1b263b 415a77 778da9'],
    ['Teal & orange', 'Cool', '00303d 006d77 83c5be ffddd2 e29578'],
    ['Moonlight', 'Cool', '0a0f1e 1c2a4a 4a6fa5 a9c4eb eef4ff'],
    ['Lagoon', 'Cool', '073b4c 118ab2 06d6a0 ffd166 ef476f'],
    ['Ice cave', 'Cool', '00111c 001a2c 003554 00a6fb ade8f4'],
    ['Storm', 'Cool', '22223b 4a4e69 9a8c98 c9ada7 f2e9e4'],
    // Pastel / dreamy
    ['Cotton candy', 'Pastel', 'ffc8dd ffafcc bde0fe a2d2ff cdb4db'],
    ['Lavender haze', 'Pastel', 'e0c3fc c8b6ff b8c0ff bbd0ff d6e4ff'],
    ['Mint cream', 'Pastel', 'd8f3dc b7e4c7 95d5b2 74c69d 52b788'],
    ['Sorbet', 'Pastel', 'fec5bb fcd5ce fae1dd f8edeb e8e8e4'],
    ['Dreamy', 'Pastel', 'f9c6c9 f5e6e8 d5c6e0 aaa1c8 967aa1'],
    ['Lilac', 'Pastel', 'f1e3f3 c2bbf0 8fb8ed 62bfed 3590f3'],
    ['Seafoam', 'Pastel', 'e8fcf6 b8f2e6 aed9e0 5e6472 ffa69e'],
    ['Blush', 'Pastel', 'fff1e6 fde2e4 fad2e1 e2ece9 bee1e6'],
    ['Rose gold', 'Pastel', '3d2b2b b76e79 e0a899 f2d0c4 fff1ec'],
    ['Pastel rainbow', 'Pastel', 'ffadad ffd6a5 fdffb6 caffbf 9bf6ff'],
    // Nature
    ['Forest', 'Nature', '081c15 1b4332 2d6a4f 52b788 b7e4c7'],
    ['Moss', 'Nature', '283618 606c38 dda15e bc6c25 fefae0'],
    ['Aurora', 'Nature', '020611 0b3d3a 3dffb5 9b5cff f3fff9'],
    ['Jungle', 'Nature', '004b23 006400 38b000 70e000 ccff33'],
    ['Earth', 'Nature', '3e2723 6d4c41 a1887f d7ccc8 efebe9'],
    ['Cherry blossom', 'Nature', '2b2d42 8d99ae edf2f4 ffb7c5 ef233c'],
    ['Lagoon sunset', 'Nature', '264653 2a9d8f e9c46a f4a261 e76f51'],
    ['Wildflower', 'Nature', '5f0f40 9a031e fb8b24 e36414 0f4c5c'],
    ['Savanna', 'Nature', '3d2b1f 8a6f45 c9a66b e6d3a3 f7efd8'],
    ['Coral reef', 'Nature', '05668d 028090 00a896 02c39a f0f3bd'],
    // Retro / film
    ['70s', 'Retro', '3d1c02 8c3b0f d97d0d f2b705 f2e6c9'],
    ['80s arcade', 'Retro', '000000 ff004d ffec27 00e436 29adff'],
    ['Game Boy', 'Retro', '0f380f 306230 8bac0f 9bbc0f e0f8d0'],
    ['Polaroid', 'Retro', 'f4ecd8 e3c9a8 c49a6c 8b5e3c 3e2f22'],
    ['Kodachrome', 'Retro', '1d2a3a 2e5e8c d9b44a c2402b f2e8cf'],
    ['VHS', 'Retro', '1a1a2e 16213e 0f3460 e94560 f5f5f5'],
    ['Diner', 'Retro', 'ef476f ffd166 06d6a0 118ab2 073b4c'],
    ['Pop art', 'Retro', 'ff006e ffbe0b 3a86ff 8338ec fb5607'],
    ['Bauhaus', 'Retro', '1d1d1b e63946 f1c40f 1d3557 f1faee'],
    ['Mid-century', 'Retro', '264653 e9c46a f4a261 e76f51 2a9d8f'],
    ['Sepia', 'Retro', '2b1d0e 5c4033 8e6e53 c2a383 eee0cb'],
    ['Super 8', 'Retro', '2a1a12 6b4226 c08552 e8c39e fff1d6'],
    // Mono / minimal
    ['Noir', 'Mono', '000000 1a1a1a 4d4d4d b3b3b3 ffffff'],
    ['Paper', 'Mono', 'f5f0e6 e0d8c8 a69f91 5c574f 1f1d1a'],
    ['Graphite', 'Mono', '0b0c0e 1e2126 3a3f47 7d8590 e6e8eb'],
    ['Ink & gold', 'Mono', '0a0a0a 1c1c1c 3d3d3d c9a227 f5e6b8'],
    ['Blueprint', 'Mono', '0a2342 2a4d7a 6f93c4 c5d9f2 ffffff'],
    ['Red accent', 'Mono', '0f0f0f 2e2e2e 8a8a8a f0f0f0 e63946'],
    ['Cream', 'Mono', 'fffdf7 f5efe0 e6dcc4 c9bc9f 8a7e66'],
    ['Slate', 'Mono', '0f172a 1e293b 334155 64748b cbd5e1'],
    ['Matrix', 'Mono', '000000 003b00 008f11 00ff41 d0ffd8'],
    ['Amber terminal', 'Mono', '0d0700 3d2600 b36b00 ffb000 ffe0a0'],
    // Bold / genre
    ['Techno', 'Genre', '050505 1a1a1a ff0040 00e5ff ffffff'],
    ['House', 'Genre', '1b1035 5b2a86 f15bb5 fee440 00bbf9'],
    ['Trap', 'Genre', '0b0b0b 3d0066 9d00ff ff007a ffd000'],
    ['Drum & bass', 'Genre', '00090f 003049 00b4d8 ff5400 ffbd00'],
    ['Lo-fi', 'Genre', '2d2a32 6c5b7b c06c84 f67280 f8b195'],
    ['Ambient', 'Genre', '0b1d26 1f4e5f 79a3b1 d0e1e6 fcf8ec'],
    ['Rock', 'Genre', '0d0d0d 3b0b0b 8b0000 d9a441 f2f2f2'],
    ['Metal', 'Genre', '000000 202020 595959 b30000 e6e6e6'],
    ['Hip-hop gold', 'Genre', '0b0b0b 262626 b8860b ffd700 ffffff'],
    ['Pop', 'Genre', 'ff4d6d ff8fa3 ffd6e0 7bdff2 b2f7ef'],
    ['Jazz', 'Genre', '1b1b2f 162447 1f4068 e43f5a f5d6ba'],
    ['Reggae', 'Genre', '0b0b0b 1e7b1e f2c500 d62828 f5f5f5'],
    ['K-pop', 'Genre', 'ff99c8 fcf6bd d0f4de a9def9 e4c1f9'],
    ['Phonk', 'Genre', '0a0005 2b0016 8c0037 ff2e63 f9ed69'],
    ['Hyperpop', 'Genre', 'ff00e5 00fff7 fff500 7a00ff ffffff'],
    ['Classical', 'Genre', '1c1814 4a3f35 8c7a5b d4c39f f7f1e3'],
    ['Synth pop', 'Genre', '0d0221 261447 2de2e6 f6019d ff6c11'],
    ['Dubstep', 'Genre', '000000 1a0033 6600ff 00ff99 ccff00'],
    ['Afrobeat', 'Genre', '2b2118 c75000 f2a900 008753 f5ead6'],
    ['Country', 'Genre', '3b2a1a 7a5230 b88b4a e3c58e f6efe2'],
  ];
  const PALETTES = PAL.map(([name, cat, hex]) => ({ name, cat, colors: hex.split(' ').map((h) => `#${h}`) }));
  const palette = (name) => PALETTES.find((p) => p.name.toLowerCase() === String(name).toLowerCase())?.colors || null;

  // ---------- looks: [name, category, palette (name or 'hex …'), 'filter key=value … | filter …', description] ----------
  const LK = [
    // Forgeheart
    ['Forgeheart', 'Forgeheart', 'Forgeheart', 'bloom intensity=1.2 threshold=0.55 tint=#ffd75e | grade look=forgeheart | vignette amount=0.55', 'The house look: gold glow, ember grade, dark corners'],
    ['Forge ember', 'Forgeheart', 'Forge ember', 'halation strength=1.2 tint=#ff5a1f | grain amount=0.25 | vignette amount=0.6', 'Hot embers bleeding into black'],
    ['Anvil strike', 'Forgeheart', 'Spark & steel', 'kickshake amount=0.8 | starburst strength=1.4 | grade look=forgeheart mix=0.7', 'Metal sparks on every kick'],
    ['Rune glow', 'Forgeheart', 'Rune violet', 'neonglow color=#bd8bff rainbow=false strength=3 | bloom tint=#bd8bff intensity=1', 'Violet runes glowing in the dark'],
    ['Molten core', 'Forgeheart', 'Molten core', 'gradientmap-fire | bloom intensity=1.6 threshold=0.5 | heathaze amount=0.5', 'Lava colors with heat shimmer'],
    ['Quench', 'Forgeheart', 'Quench blue', 'grade look=cold blue | anamorphic tint=#48ddff | grain amount=0.2', 'Steel cooling in blue water'],
    ['Hearth fire', 'Forgeheart', 'Hearth glow', 'dreamglow tint=#ffcc88 amount=0.7 | lightleak color1=#ff8c42 color2=#ffd75e | vignette', 'Warm and cozy, like sitting by the fire'],
    ['Arcane forge', 'Forgeheart', 'Arcane forge', 'chromatic amount=0.6 | bloom tint=#bd8bff | grade look=cyberpunk mix=0.6', 'Magic violet with gold sparks'],
    ['Forge HUD', 'Forgeheart', 'Forgeheart', 'scanframe color=#ffd75e | scanlines intensity=0.3 | bloom intensity=0.8', 'Game-like gold HUD frame'],
    ['Slag', 'Forgeheart', 'Slag & gold', 'bleach amount=0.6 | grain amount=0.4 | vignette amount=0.7', 'Gritty desaturated metal'],
    ['Gold dust', 'Forgeheart', 'Ink & gold', 'hatsglitter color=#ffd75e density=2 | bloom tint=#ffd75e | vignette', 'Gold sparkles on the hi-hats'],
    ['Ember rain', 'Forgeheart', 'Firelight', 'melt amount=0.8 | bloom intensity=1.3 tint=#ff8c42', 'Glowing drips falling down'],
    ['Blade edge', 'Forgeheart', 'Spark & steel', 'outline color=#ffd75e background=#0b0d12 | bloom tint=#ffd75e', 'Gold outlines on black'],
    ['Crucible', 'Forgeheart', 'Molten core', 'tritone shadows=#1a0500 mids=#c2410c highlights=#ffe28a | bloom intensity=1.5', 'Three-tone molten metal'],
    ['Forgeheart pixel', 'Forgeheart', 'Forgeheart', 'bitcrush bits=3 pixel=4 | bloom intensity=0.7', 'Retro game Forgeheart'],
    // Cinematic
    ['Blockbuster', 'Cinematic', 'Teal & orange', 'grade look=teal & orange | anamorphic | letterbox | grain amount=0.15', 'Teal and orange, wide bars, blue flares'],
    ['Noir', 'Cinematic', 'Noir', 'grade look=noir | grain amount=0.4 | vignette amount=0.8', 'Hard black and white'],
    ['Bleach bypass', 'Cinematic', 'Graphite', 'bleach | grain amount=0.3 | vignette', 'Silvery, gritty war-movie look'],
    ['Golden hour', 'Cinematic', 'Golden hour', 'grade look=warm film | lightleak strength=0.5 | dreamglow amount=0.4', 'Warm late-afternoon sun'],
    ['Moonlit', 'Cinematic', 'Moonlight', 'grade look=moonlight | dreamglow amount=0.4 tint=#cfe3ff | vignette', 'Blue night scene'],
    ['Thriller', 'Cinematic', 'Deep sea', 'grade look=matrix mix=0.6 | sharpen amount=0.6 | vignette amount=0.8', 'Sickly green tension'],
    ['Epic trailer', 'Cinematic', 'Teal & orange', 'godrays strength=1.4 | anamorphic strength=1.4 | letterbox | grade look=teal & orange', 'Light shafts, flares, bars'],
    ['Pro-Mist', 'Cinematic', 'Sorbet', 'dreamglow amount=0.9 | halation strength=0.5 | grade look=faded pastel mix=0.5', 'Soft blooming highlights'],
    ['Desert road', 'Cinematic', 'Desert', 'grade look=desert | heathaze | grain amount=0.2', 'Hot dusty highway'],
    ['Emerald city', 'Cinematic', 'Forest', 'grade look=emerald | bloom tint=#9dffb0 | vignette', 'Rich greens'],
    ['Tilt-shift town', 'Cinematic', 'Lagoon sunset', 'tiltshift | adjust saturation=1.4 contrast=1.15', 'Everything looks like a miniature'],
    ['Lens flare', 'Cinematic', 'Golden hour', 'lensflare strength=1.2 | bloom intensity=0.8 | grade look=warm film mix=0.5', 'Sun flares and glow'],
    ['Widescreen', 'Cinematic', 'Graphite', 'letterbox | grade look=cold blue mix=0.5 | grain amount=0.15', 'Cinemascope bars and cool grade'],
    ['Rose gold', 'Cinematic', 'Rose gold', 'grade look=rose gold | dreamglow amount=0.5 tint=#ffd6cc', 'Soft pink metallic'],
    ['Sunset drive', 'Cinematic', 'Sunset', 'grade look=sunset | lightleak | anamorphic tint=#ff9a6a', 'Purple-orange evening'],
    // Retro / film
    ['VHS home video', 'Retro', 'VHS', 'tape | vhs | vignette amount=0.4', 'A camcorder tape from 1994'],
    ['Super 8 memory', 'Retro', 'Super 8', 'super8 | lightleak strength=0.5', 'Warm home movie film'],
    ['Old TV', 'Retro', 'Noir', 'crtroll | grain amount=0.3', 'A flickering tube TV'],
    ['Arcade', 'Retro', '80s arcade', 'crt-arcade | bloom intensity=1', 'Curved arcade cabinet screen'],
    ['Game Boy', 'Retro', 'Game Boy', 'dither-gameboy', 'Four shades of green'],
    ['8-bit', 'Retro', '80s arcade', 'bitcrush-nes | scanlines intensity=0.3', 'Console pixels'],
    ['Polaroid', 'Retro', 'Polaroid', 'grade look=faded pastel | grain amount=0.25 | vignette amount=0.5 | border thickness=40 radius=0 color=#f4ecd8 glow=0', 'Instant photo with a white frame'],
    ['Kodachrome', 'Retro', 'Kodachrome', 'grade look=kodachrome | grain amount=0.2', 'Saturated slide film'],
    ['Sepia print', 'Retro', 'Sepia', 'sepia | dust amount=0.5 | vignette amount=0.6', 'Old brown photograph'],
    ['Found footage', 'Retro', 'Graphite', 'vhs-worn | dust | gateweave', 'Lost tape horror'],
    ['Newspaper', 'Retro', 'Paper', 'halftone colors=ink | grain amount=0.15', 'Printed dots on paper'],
    ['Comic', 'Retro', 'Pop art', 'toon levels=4 | cmyk dot=5 black=0.6', 'Inked cartoon with print dots'],
    ['Magazine', 'Retro', 'Bauhaus', 'cmyk dot=6', 'Four-color print'],
    ['Pixel art', 'Retro', 'Diner', 'pixelate size=8 levels=6', 'Chunky pixels'],
    ['Teletext', 'Retro', 'Glitch RGB', 'pixelate size=12 levels=2 | scanlines', 'Blocky TV text page'],
    ['70s show', 'Retro', '70s', 'grade look=warm film | dreamglow amount=0.4 | grain amount=0.3 | vignette', 'Warm hazy seventies'],
    ['Daguerreotype', 'Retro', 'Sepia', 'sepia tone=#9c8b6e | gateweave | dust amount=1.2 | vignette amount=0.9', 'The oldest photo look'],
    ['Silent film', 'Retro', 'Noir', 'grade look=noir | super8 warmth=0 | letterbox-43', 'Flickering black and white, 4:3'],
    ['Camcorder 2003', 'Retro', 'Midnight', 'jpeg quality=18 | timecode | sharpen amount=0.8', 'Early digital video'],
    ['Lomo', 'Retro', 'Lagoon', 'adjust saturation=1.5 contrast=1.3 | vignette amount=1 | lightleak strength=0.6', 'Toy camera: punchy and vignetted'],
    // Neon / club
    ['Synthwave', 'Neon', 'Synthwave', 'grade look=vaporwave | bloom intensity=1.4 | scanlines intensity=0.25', 'Pink and cyan glow with scanlines'],
    ['Cyberpunk', 'Neon', 'Cyberpunk', 'grade look=cyberpunk | chromatic amount=0.8 | bloom intensity=1.2', 'Neon city at night'],
    ['Neon edges', 'Neon', 'Blacklight', 'neonglow | trails decay=0.85', 'Glowing outlines with trails'],
    ['Club strobe', 'Neon', 'Club red', 'strobe-kick | bloom intensity=1.2 | kickshake amount=0.4', 'Flashes and shakes on kicks'],
    ['Laser room', 'Neon', 'Laser show', 'starburst points=4 | bloom intensity=1.6 | vignette', 'Sparkling lasers'],
    ['Blacklight', 'Neon', 'Blacklight', 'neonize | bloom intensity=1.2', 'UV paint glow'],
    ['Acid', 'Neon', 'Acid rave', 'huecycle speed=2 jump=0.4 | wavewarp | bloom', 'Melting rainbow trip'],
    ['Hologram', 'Neon', 'Hologram', 'prism mix=0.5 | scanlines spacing=4 intensity=0.35 | chromatic amount=0.5', 'Iridescent projection'],
    ['Tron', 'Neon', 'Tokyo night', 'outline color=#2bd9ff background=#020611 | bloom tint=#2bd9ff intensity=1.5', 'Blue light lines on black'],
    ['Miami vice', 'Neon', 'Miami', 'grade look=vaporwave mix=0.7 | bloom intensity=1 | lightleak color1=#ff2a6d color2=#05d9e8', 'Pink and teal heat'],
    ['Ultraviolet', 'Neon', 'Ultraviolet', 'gradientmap c1=#0c0032 c2=#3500d3 c3=#ff2bd6 c4=#ffffff | bloom', 'Everything in UV'],
    ['LED stadium', 'Neon', 'Techno', 'ledwall size=10 | bloom intensity=1', 'A giant LED screen'],
    ['Rave tunnel', 'Neon', 'Acid rave', 'zoomfeedback | huecycle speed=1.5', 'Infinite colored tunnel'],
    ['Night drive', 'Neon', 'Synth pop', 'anamorphic tint=#ff2bd6 | grade look=cyberpunk mix=0.5 | trails decay=0.8', 'City lights streaking by'],
    ['Disco', 'Neon', 'House', 'hatsglitter density=3 | starburst | huecycle speed=0.5 saturation=1.3', 'Glitter ball sparkle'],
    // Glitch
    ['Datamosh', 'Glitch', 'Glitch RGB', 'moshbloom | rgbsplit amount=0.5', 'Melting compression art'],
    ['Corrupted', 'Glitch', 'Glitch RGB', 'blockglitch | digitalnoise | rgbsplit', 'A broken file'],
    ['Signal lost', 'Glitch', 'VHS', 'tape dropouts=2 | scantear | digitalnoise amount=0.3', 'Breaking-up broadcast'],
    ['Pixel sort', 'Glitch', 'Hyperpop', 'pixelsort | chromaglitch amount=0.3', 'Streaked sorted pixels'],
    ['JPEG hell', 'Glitch', 'Glitch RGB', 'jpeg quality=5 blocky=0.9 | bitcrush bits=4 pixel=1', 'Compressed to death'],
    ['RGB punch', 'Glitch', 'Techno', 'rgbsplit amount=1.2 react=1.5 | kickshake amount=0.6', 'Color split on every kick'],
    ['Error screen', 'Glitch', 'Graphite', 'interlace | blockglitch rate=20 | scanlines', 'A screen about to crash'],
    ['Melt down', 'Glitch', 'Hyperpop', 'moshmelt amount=0.7 | huecycle speed=0.5', 'Frames dripping into each other'],
    ['Freeze frame', 'Glitch', 'Midnight', 'moshfreeze amount=0.5 | rgbsplit amount=0.4', 'Blocks stuck in time'],
    ['Broken LCD', 'Glitch', 'Glitch RGB', 'channelmix swap=rgb → bgr mix=0.4 | blockglitch amount=0.4 | chromaglitch', 'Cracked display'],
    ['Wave tear', 'Glitch', 'VHS', 'wobble amount=1.2 | interlace offset=0.4', 'Wobbly torn video'],
    ['Glitch subtle', 'Glitch', 'Graphite', 'glitch-subtle | grain amount=0.15', 'Small tasteful glitches'],
    ['Hyperpop', 'Glitch', 'Hyperpop', 'rgbsplit amount=0.8 | bloom intensity=1.4 | huecycle jump=0.5 speed=0', 'Loud and colorful'],
    ['Slit scan', 'Glitch', 'Synthwave', 'slitscan | bloom', 'Time smeared sideways'],
    ['Digital rain', 'Glitch', 'Matrix', 'asciimatrix | bloom tint=#38ff6a', 'Falling green code'],
    // Dreamy / soft
    ['Dreamy', 'Dreamy', 'Dreamy', 'dreamglow amount=0.9 | grade look=faded pastel | grain amount=0.1', 'Soft and hazy'],
    ['Cotton candy', 'Dreamy', 'Cotton candy', 'gradientmap c1=#a2d2ff c2=#cdb4db c3=#ffafcc c4=#fff0f6 mix=0.7 | dreamglow', 'Pastel sugar'],
    ['Underwater', 'Dreamy', 'Ocean', 'wavewarp ampX=0.6 ampY=0.6 | grade look=cold blue | godrays y=1 tint=#9ff3ff', 'Rippling under the surface'],
    ['Heaven', 'Dreamy', 'Blush', 'bloom intensity=2 threshold=0.4 | godrays strength=1.2 | adjust brightness=0.1', 'Bright, glowing, rays'],
    ['Lo-fi', 'Dreamy', 'Lo-fi', 'grade look=faded pastel | grain amount=0.3 | vignette amount=0.4', 'Chill beats to study to'],
    ['Echo dream', 'Dreamy', 'Lavender haze', 'echo | dreamglow amount=0.5', 'Echoes fading into each other'],
    ['Snow globe', 'Dreamy', 'Arctic', 'frosted amount=0.4 | bloom tint=#e0fbfc | vignette', 'Seen through frosty glass'],
    ['Ghostly', 'Dreamy', 'Moonlight', 'ghost | grade look=moonlight | dreamglow', 'Faint onion-skin trails'],
    ['Watercolor', 'Dreamy', 'Sorbet', 'oilpaint radius=4 | adjust saturation=0.8 brightness=0.05 | grain amount=0.1', 'Soft painted look'],
    ['Long exposure', 'Dreamy', 'Midnight', 'trails-long | bloom', 'Light painting trails'],
    ['Mirage', 'Dreamy', 'Desert', 'heathaze amount=1 | dreamglow amount=0.4', 'Shimmering hot air'],
    ['Kaleido dream', 'Dreamy', 'Pastel rainbow', 'kaleido segments=8 | dreamglow', 'Soft kaleidoscope'],
    ['Lucid', 'Dreamy', 'Lilac', 'liquid | huecycle speed=0.3', 'Flowing like paint'],
    ['Aurora sky', 'Dreamy', 'Aurora', 'bloom tint=#3dffb5 | grade look=emerald mix=0.5 | grain amount=0.1', 'Northern lights green'],
    ['Halo', 'Dreamy', 'Rose gold', 'halation strength=1.2 tint=#ffb38a | dreamglow amount=0.5', 'Glowing edges'],
    // Art / stylized
    ['Pencil', 'Art', 'Paper', 'sketch', 'Pencil drawing'],
    ['Ink etching', 'Art', 'Paper', 'crosshatch', 'Cross-hatched ink'],
    ['Oil painting', 'Art', 'Autumn', 'oilpaint | adjust saturation=1.2', 'Thick painted strokes'],
    ['Cartoon', 'Art', 'Pop art', 'toon', 'Flat cel shading with outlines'],
    ['Stained glass', 'Art', 'Wildflower', 'crystal edges=1 | adjust saturation=1.4', 'Colored glass cells'],
    ['Mosaic', 'Art', 'Mid-century', 'hexpixel-big', 'Big hexagon tiles'],
    ['Low poly', 'Art', 'Lagoon sunset', 'trimosaic', 'Triangle facets'],
    ['Blueprint', 'Art', 'Blueprint', 'outline color=#c5d9f2 background=#0a2342 | scanlines spacing=6 intensity=0.15', 'Technical drawing'],
    ['ASCII art', 'Art', 'Mono', 'ascii', 'Characters'],
    ['Terminal', 'Art', 'Amber terminal', 'asciidense colors=false tint=#ffb000 | scanlines intensity=0.3 | bloom tint=#ffb000', 'Amber text screen'],
    ['Topographic', 'Art', 'Blueprint', 'contours colors=false line=#c5d9f2 keep=0.1', 'Contour map lines'],
    ['Engraving', 'Art', 'Paper', 'stripes ink=#1f1d1a background=#f5f0e6 spacing=6', 'Banknote-style lines'],
    ['Pop poster', 'Art', 'Pop art', 'posterize-3 | adjust saturation=1.6', 'Flat bold screen print'],
    ['Duotone pink', 'Art', 'Cotton candy', 'duotone shadows=#2b0b3f highlights=#ff8fab', 'Two-color poster'],
    ['Duotone blue', 'Art', 'Ocean', 'duotone shadows=#03045e highlights=#90e0ef', 'Cool two-color poster'],
    ['Risograph', 'Art', 'Diner', 'tritone shadows=#1d3557 mids=#ef476f highlights=#f1faee | grain amount=0.35 size=2', 'Grainy riso print'],
    ['Emboss', 'Art', 'Graphite', 'emboss color=0.1', 'Stamped metal relief'],
    ['Mandala', 'Art', 'Wildflower', 'mandala', 'Kaleidoscopic rings'],
    ['Little planet', 'Art', 'Lagoon', 'polar-to', 'The picture wrapped into a planet'],
    ['Mirror world', 'Art', 'Synthwave', 'mirror-quad | bloom', 'Four-way symmetry'],
    // Mono / minimal
    ['Clean B&W', 'Mono', 'Noir', 'adjust saturation=0 contrast=1.2', 'Simple black and white'],
    ['High contrast', 'Mono', 'Noir', 'levels black=0.2 white=0.8 | adjust saturation=0', 'Crushed blacks and whites'],
    ['1-bit', 'Mono', 'Noir', 'dither-1bit', 'Black and white dots'],
    ['Silver', 'Mono', 'Graphite', 'adjust saturation=0 | bloom intensity=0.6 | grain amount=0.2', 'Glowing silver'],
    ['Red only', 'Mono', 'Red accent', 'selectivecolor keep=#e63946', 'Black and white except red'],
    ['Gold only', 'Mono', 'Ink & gold', 'selectivecolor keep=#ffd75e range=0.1', 'Black and white except gold'],
    ['Night vision', 'Mono', 'Matrix', 'nightvision', 'Green night goggles'],
    ['Thermal', 'Mono', 'Firelight', 'thermal', 'Heat camera'],
    ['Infrared', 'Mono', 'Cherry blossom', 'infrared', 'Pink false-color foliage'],
    ['X-ray', 'Mono', 'Blueprint', 'invert amount=1 | adjust saturation=0 | colorize color=#9ff3ff mix=0.6', 'Inverted blue negative'],
    // Music-driven
    ['Kick punch', 'Beat', 'Techno', 'basszoom | kickshake amount=0.5 | bloom react=1', 'Everything punches on kicks'],
    ['Snare flash', 'Beat', 'Club red', 'snareflash | rgbsplit react=1.5 amount=0.3', 'White flash and split on snares'],
    ['Drop boom', 'Beat', 'Hyperpop', 'dropboom | bloom intensity=1.2 react=1', 'Huge impact on the drop'],
    ['Strobe club', 'Beat', 'Techno', 'strobe rate=half beats duty=0.12 | bloom', 'Half-beat strobes'],
    ['Blackout', 'Beat', 'Noir', 'strobe-blackout', 'Blackouts on the beat'],
    ['Heartbeat', 'Beat', 'Club red', 'pulsevignette color=#3d0000 | basszoom amount=0.4', 'Red pulse on every kick'],
    ['Shatter', 'Beat', 'Glitch RGB', 'beatsplit | rgbsplit', 'The frame shatters on hits'],
    ['Bass wobble', 'Beat', 'Dubstep', 'fisheye react=1.2 | wavewarp drive=bass react=1.5', 'The bass bends the picture'],
    ['Hi-hat sparkle', 'Beat', 'House', 'hatsglitter | bloom', 'Sparkles on every hat'],
    ['Ripple kick', 'Beat', 'Ocean', 'ripple | bloom tint=#90e0ef', 'Kicks send ripples'],
    ['Invert hits', 'Beat', 'Noir', 'beatinvert drive=snare', 'Negative flash on snares'],
    ['Beat sweep', 'Beat', 'Ink & gold', 'shine | bloom', 'A shine sweeps every beat'],
    ['Echo pump', 'Beat', 'Synthwave', 'echo react=1 | bloom', 'Echoes pump with the kick'],
    ['Pulse grid', 'Beat', 'Techno', 'tile tiles=2 react=1.5 | rgbsplit', 'The grid multiplies on kicks'],
    ['Bass zoom blur', 'Beat', 'Drum & bass', 'zoomblur drive=bass react=2', 'Zoom blur with the bass'],
    // Social-ready
    ['Story clean', 'Social', 'Pop', 'adjust saturation=1.2 contrast=1.1 | sharpen amount=0.4', 'Punchy and clean for stories'],
    ['Reel glow', 'Social', 'House', 'bloom intensity=1 | grade look=vaporwave mix=0.4 | vignette amount=0.3', 'Glowy and vibrant'],
    ['Framed post', 'Social', 'Cream', 'border color=#fffdf7 thickness=30 radius=20 glow=0 | grade look=faded pastel mix=0.5', 'Clean white frame'],
    ['Neon frame', 'Social', 'Synthwave', 'border rainbow=true glow=1.5 thickness=10 radius=40 | bloom', 'Rainbow glowing frame'],
    ['Viewfinder', 'Social', 'Graphite', 'scanframe | timecode | grain amount=0.15', 'Recording camera overlay'],
    ['Square crop', 'Social', 'Mono', 'letterbox-square', 'A 1:1 square inside any frame'],
    ['Album cover', 'Social', 'Kodachrome', 'grade look=kodachrome | grain amount=0.2 | vignette amount=0.5', 'Print-ready warm grade'],
    ['Lyric video', 'Social', 'Midnight', 'blur radius=10 | adjust brightness=-0.15 | vignette', 'Blurred dark background for text'],
  ];
  const parseFx = (s) => s.split('|').map((part) => {
    const p = part.trim();
    const id = p.split(/\s+/)[0];
    const values = {};
    for (const m of p.slice(id.length).matchAll(/(\w+)=([^=]+?)(?=\s+\w+=|$)/g)) {
      const v = m[2].trim();
      values[m[1]] = v === 'true' ? true : v === 'false' ? false : /^-?[\d.]+$/.test(v) ? Number(v) : v;
    }
    return { id, values };
  }).filter((x) => x.id);
  const LOOKS = LK.map(([name, cat, pal, fx, desc]) => ({ name, cat, desc, colors: palette(pal) || pal.split(' ').map((h) => `#${h}`), fx: parseFx(fx) }));

  // ---------- blend presets: [name, blend mode, opacity, description] ----------
  const BLEND_PRESETS = [
    ['Glow', 'add', 1, 'Adds light: black disappears, bright parts glow'],
    ['Soft glow', 'add', 0.6, 'A gentler additive glow'],
    ['Screen', 'screen', 1, 'Brightens without blowing out (light leaks, smoke)'],
    ['Light veil', 'screen', 0.5, 'A thin bright veil'],
    ['Overlay punch', 'overlay', 1, 'Contrasty mix: textures, grain, gradients'],
    ['Soft overlay', 'soft-light', 0.8, 'Subtle tint and contrast'],
    ['Hard light', 'hard-light', 1, 'Strong colored light'],
    ['Multiply shadows', 'multiply', 1, 'Darkens: white disappears (paper, shadows, ink)'],
    ['Ink', 'multiply', 0.7, 'A lighter multiply'],
    ['Darken', 'darken', 1, 'Keeps the darker of the two'],
    ['Lighten', 'lighten', 1, 'Keeps the lighter of the two'],
    ['Difference flip', 'difference', 1, 'Psychedelic inverted overlaps'],
    ['Exclusion', 'exclusion', 1, 'Softer, pastel difference'],
    ['Color dodge', 'color-dodge', 1, 'Burning bright highlights'],
    ['Color burn', 'color-burn', 1, 'Deep saturated darks'],
    ['Hue only', 'hue', 1, 'Takes only this layer\'s hue'],
    ['Saturation only', 'saturation', 1, 'Takes only this layer\'s saturation'],
    ['Color only', 'color', 1, 'Colors the layers below (keeps their brightness)'],
    ['Luminosity only', 'luminosity', 1, 'Takes only this layer\'s brightness'],
    ['Ghost', 'normal', 0.35, 'Normal, mostly see-through'],
    ['Half', 'normal', 0.5, 'Normal at 50%'],
    ['Solid', 'normal', 1, 'Back to normal, fully opaque'],
  ].map(([name, blend, opacity, desc]) => ({ name, blend, opacity, desc }));

  // ---------- keyframe eases (ThreeLayers.evalKeys knows them all) ----------
  const EASES = [
    ['linear', 'Linear', 'Constant speed'], ['ease', 'Smooth', 'Eases in and out (the default)'], ['hold', 'Hold', 'Stays, then jumps'],
    ['in', 'Ease in', 'Starts slow, ends fast (cubic)'], ['out', 'Ease out', 'Starts fast, settles slowly (cubic)'], ['inOut', 'Ease in-out', 'Slow, fast, slow (cubic)'],
    ['quadIn', 'Gentle in', 'A softer ease in'], ['quadOut', 'Gentle out', 'A softer ease out'],
    ['quartIn', 'Strong in', 'A heavy ease in'], ['quartOut', 'Strong out', 'A heavy ease out'], ['quartInOut', 'Strong in-out', 'Snappy middle'],
    ['expoIn', 'Expo in', 'Almost still, then shoots off'], ['expoOut', 'Expo out', 'Snaps in, then glides (great for punches)'], ['expoInOut', 'Expo in-out', 'Very snappy middle'],
    ['sineIn', 'Sine in', 'Gentle start'], ['sineOut', 'Sine out', 'Gentle stop'], ['sineInOut', 'Sine in-out', 'Like a pendulum'],
    ['circIn', 'Circular in', 'Accelerates hard at the end'], ['circOut', 'Circular out', 'Fast start, long tail'],
    ['backIn', 'Anticipate', 'Pulls back first, then goes'], ['backOut', 'Overshoot', 'Goes a bit too far, then settles'], ['backInOut', 'Anticipate + overshoot', 'Both ends'],
    ['elastic', 'Elastic', 'Springs past the value and wobbles back'], ['elasticIn', 'Elastic in', 'Wind-up wobble before moving'],
    ['bounce', 'Bounce', 'Lands and bounces'], ['bounceIn', 'Bounce in', 'Bounces before taking off'],
    ['smoother', 'Smoother', 'An extra smooth in-out'], ['steps4', '4 steps', 'Jumps in 4 steps'], ['steps8', '8 steps', 'Jumps in 8 steps'],
    ['wobble', 'Wobble', 'Shakes and settles on the value'], ['pulse', 'Pulse', 'Goes to the value and comes back'],
  ].map(([id, name, desc]) => ({ id, name, desc }));

  return { PALETTES, palette, LOOKS, BLEND_PRESETS, EASES, parseFx };
})();
